Repository pucardotorg/dristi-solutions, pull requests merged in 2024-09, with the labels that each got.

#58 Dpg backend drop sep 5 ii
  backend/analytics/.gitignore
  backend/analytics/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/analytics/src/main/java/org/pucar/dristi/kafka/consumer/EventListener.java
  backend/analytics/src/main/java/org/pucar/dristi/service/BillingService.java
  backend/analytics/src/main/java/org/pucar/dristi/util/BillingUtil.java
  backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
  backend/analytics/src/main/resources/application.properties
  backend/analytics/src/test/java/org/pucar/dristi/kafka/consumer/EventListenerTest.java
  backend/analytics/src/test/java/org/pucar/dristi/service/BillingServiceTest.java
  backend/analytics/src/test/java/org/pucar/dristi/util/BillingUtilTest.java
  backend/analytics/src/test/java/org/pucar/dristi/util/IndexerUtilsTest.java
  backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
  backend/application/src/test/java/org/pucar/dristi/service/PaymentUpdateServiceTest.java
Labels: Backend Drop

#75 summons getting triggered two times, fixed that
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#99 changed filestoreId for order review modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
Labels: UI

#100 enable mark attendance in hearing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/MarkAttendance.js
Labels: UI

#108 Change pending task scheduler
  backend/scheduler-svc/src/main/java/digit/util/PendingTaskUtil.java
  backend/scheduler-svc/src/test/java/digit/util/PendingTaskUtilTest.java
Labels: bug, Backend, UAT

#110 optout changes in generate order and Schedule Hearing flow, closing o…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#127 FileStoreUtilUpdate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/fileStoreUtil.js
Labels: bug, UI

#133 casemanagement mdms issue fix.
  backend/casemanagement/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/casemanagement/src/main/java/org/pucar/dristi/service/ServiceUrlMapperVCService.java
  backend/casemanagement/src/main/java/org/pucar/dristi/util/MdmsV2Util.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/MdmsSearch.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/SchemaDefCriteria.java
  backend/casemanagement/src/main/resources/application.properties
Labels: Backend

#131 casemanagement mdms issue fix.
  backend/casemanagement/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/casemanagement/src/main/java/org/pucar/dristi/service/ServiceUrlMapperVCService.java
  backend/casemanagement/src/main/java/org/pucar/dristi/util/MdmsV2Util.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/MdmsSearch.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/SchemaDefCriteria.java
  backend/casemanagement/src/main/resources/application.properties
Labels: Backend

#142 Summons Order Hearing Date Not AutoFilled-> Fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: bug, UI

#140 Bnss flow changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/caseWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/admissionActionConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/litigantHome/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Judge/JudgeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#126 dependabot security issue fixes (add to dpg later)
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/libraries/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/SideBar/EmployeeSideBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/useIndividualView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/useIndividualView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/useIndividualView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/useIndividualView.js
  frontend/pucar-ui/assets/pucarGlobalConfig.js
  frontend/pucar-ui/web/micro-ui-internals/packages/libraries/package.json
  utilities/dristi-pdf/package-lock.json
  utilities/dristi-pdf/package.json
  utilities/dristi-pdf/src/app.js
  utilities/dristi-pdf/src/views/error-message.jade
  utilities/dristi-pdf/src/views/error.jade
  utilities/dristi-pdf/src/views/index.jade
  utilities/dristi-pdf/src/views/layout.jade
Labels: UI

#143 redis config change
  backend/case/src/main/java/org/pucar/dristi/config/RedisConfig.java
Labels: Backend

#138 Uat v1.0.4 merge
  .github/workflows/image-build-Digit-Ui.yaml
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/fileStoreUtil.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/component.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/chequedetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/prayerAndSwornConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/witnessConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/MarkAttendance.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
Labels: UI

#128 demand create change to call on case submit
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
Labels: UI

#147 Bar registration number application pdfs
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/orderHandlers/acceptAdrApplication.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/adrCaseReferral.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
  utilities/dristi-pdf/src/orderHandlers/caseTransfer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderForInitiateReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/rejectAdrApplication.js
  utilities/dristi-pdf/src/orderHandlers/rejectReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/rescheduleRequestJudge.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
Labels: UI

#113 [issue-1337- judgement order]: config correction for microphone in sentence, localization changes, c…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#153 filled data in mandatory async submission
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
Labels: UI

#154 Added enc for case
  backend/case/pom.xml
  backend/case/src/main/java/org/pucar/dristi/Main.java
  backend/case/src/main/java/org/pucar/dristi/config/CaseEncryptionConfiguration.java
  backend/case/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/case/src/main/java/org/pucar/dristi/kafka/Producer.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseEncryptionServiceImpl.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseEncryptionServiceRestConnection.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
  backend/case/src/main/java/org/pucar/dristi/service/IndividualService.java
  backend/case/src/main/java/org/pucar/dristi/util/AdvocateUtil.java
  backend/case/src/main/java/org/pucar/dristi/util/CaseConvertClass.java
  backend/case/src/main/java/org/pucar/dristi/util/EncryptionDecryptionUtil.java
  backend/case/src/main/java/org/pucar/dristi/util/IndividualUtil.java
  backend/case/src/main/java/org/pucar/dristi/util/SpringContext.java
  backend/case/src/main/resources/application.properties
  backend/case/src/test/java/org/pucar/dristi/config/CaseEncryptionConfigurationTest.java
  backend/case/src/test/java/org/pucar/dristi/service/CaseEncryptionServiceRestConnectionTest.java
  backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java
Labels: Backend

#141 added id in opt-out table
  backend/scheduler-svc/reschedule-request-opt-out-persister.yml
  backend/scheduler-svc/src/main/java/digit/enrichment/RescheduleRequestOptOutEnrichment.java
  backend/scheduler-svc/src/main/java/digit/repository/querybuilder/RescheduleRequestOptOutQueryBuilder.java
  backend/scheduler-svc/src/main/java/digit/repository/rowmapper/RescheduleRequestOptOutRowMapper.java
  backend/scheduler-svc/src/main/java/digit/service/hearing/OptOutProcessor.java
  backend/scheduler-svc/src/main/java/digit/web/models/OptOut.java
  backend/scheduler-svc/src/main/resources/db/migration/main/V20240912115200__oo_opt_out_id_ddl.sql
  backend/scheduler-svc/src/test/java/digit/repository/querybuilder/RescheduleRequestOptOutQueryBuilderTest.java
  backend/scheduler-svc/src/test/java/digit/repository/rowmapper/RescheduleRequestOptOutRowMapperTest.java
  backend/scheduler-svc/src/test/java/digit/service/hearing/OptOutProcessorTest.java
Labels: Backend

#155 offline payment pending task closing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCopyTextDiv.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSortComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#172 filling out correct information in hearing and voluntary orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
Labels: UI

#161 fix for empty last name in witness deposition and
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
Labels: UI

#173 added logger in mdmsSerachSchema.
  common/sunbirdrc-credential-service/src/main/java/org/egov/sunbirdrc/service/MdmsSchemaService.java
Labels: Backend

#145 view a case-> submission tab-> on adjusting the size of view submission modal-> pdf is not displaying-> fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#177 shifted create demand to proceed button
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#182 added right method call in join litigant method
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
Labels: bug, Backend, QA

#183 Send back changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/caseWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/paymentType.js
Labels: UI

#185 handlers for bail bond, casetransfer, withdrawal application
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/routes/application.js
Labels: UI

#186 [UAT | Judgement Order #1337]modal for viewing judgement order in view a case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
Labels: UI

#187 enable view hearings even if no hearings scheduled for the day
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: bug, UI, UAT

#190 Sept Demo Localization changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
Labels: UI

#188 Addition of Scrolling Routing in Case Admission
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
Labels: UI

#150 ErrorMsgIntegration
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#192 longitude, latitude values corrected in update call
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
Labels: UI

#197 Added court details in the dependency array
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
Labels: UI

#204 order and submission loader, some css changes in efiling advocate
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
Labels: UI

#205 fixed orders and applications pdf bugs
  utilities/dristi-pdf/src/api.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
Labels: UI

#157 join respondent by advocate completed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/citizen/otpComponent.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/registerRespondentForm.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/components/OtpComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/RegisterRespondentForm.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/litigantHome/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/UploadIdType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#212 Delay condonation payload changes in payment calculator
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
Labels: UI

#214 original hearing date bug fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#208 Case management summons accused
  backend/casemanagement/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/casemanagement/src/main/java/org/pucar/dristi/service/PdfSummonsOrderRequestService.java
  backend/casemanagement/src/main/java/org/pucar/dristi/service/ServiceUrlMappingPdfService.java
  backend/casemanagement/src/main/java/org/pucar/dristi/util/SummonsOrderPdfUtil.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/PdfSummonsAccusedRequest.java
  backend/casemanagement/src/main/java/org/pucar/dristi/web/models/SummonsAccusedRequest.java
  backend/dristi-case-pdf/controller/caseController.js
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/kafka/SummonsConsumer.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/java/digit/util/CaseManagementUtil.java
  backend/summons-svc/src/main/java/digit/util/OrderUtil.java
  backend/summons-svc/src/main/java/digit/web/models/PdfRequest.java
  backend/summons-svc/src/main/java/digit/web/models/VcCredentialRequest.java
  backend/summons-svc/src/main/java/digit/web/models/VcEntityCriteria.java
  backend/summons-svc/src/main/java/digit/web/models/VcEntityOrderSearchRequest.java
  backend/summons-svc/src/main/java/digit/web/models/VcOrderSearchPagination.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/service/SummonsServiceTest.java
Labels: Backend

#222 fixed dates and some other changse
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
Labels: UI

#219 Denial of Upadate Api Call in Correction
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#232 Lastname undefined
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/UICustomizations.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderForInitiateReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
Labels: UI

#237 Uat issue with styling of modal , fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
Labels: UI, UAT

#240 Mdms dropdown payment
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ListOfSuretyDocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/cases/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/pucar/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/sample/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/useIndividualView.js
Labels: UI

#242 show net hearing dates from availibility api call
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
Labels: UI, UAT

#244 Uat with dev pipelines
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ListOfSuretyDocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/micro-ui/web/sonar-project.properties
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/cases/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/pucar/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/sample/src/hooks/useIndividualView.js
  frontend/pucar-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/useIndividualView.js
  utilities/dristi-pdf/Dockerfile
  utilities/dristi-pdf/migration/Dockerfile
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderForInitiateReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
Labels: UI

#245 mandatory submission pending task close, suffix add in bill
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#230 Task notice demand create
  backend/summons-svc/src/main/java/digit/channel/ChannelFactory.java
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/kafka/SummonsConsumer.java
  backend/summons-svc/src/main/java/digit/service/DemandService.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/java/digit/web/models/ChannelName.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/service/DemandServiceTest.java
Labels: Backend, QA

#252 minor fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#257 UAT join case bug fix, payment filter fix in NyayMitra
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#260 call api for available dates when opening schedule hearing from pendi…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
Labels: UI, UAT

#262 pending task fix in applications
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#259 fix bug for sat incoming
  backend/scheduler-svc/src/main/java/digit/service/CalendarService.java
  backend/scheduler-svc/src/main/java/digit/task/RequestOptOutScheduleTask.java
Labels: bug, Backend, Develop

#266 fix in challan api to send name and number
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
Labels: UI, UAT

#265 styling changes for scroll
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: bug, UI, UAT

#270 court staff summon filter fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
Labels: UI

#272 judge screen -> submissions tab-> submissions with pending esign stage should not be showing visible in table
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI, UAT

#267 Develop update uat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
Labels: UI

#276 court staff search fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
Labels: UI

#277 usertype select bug fixed uat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: bug, UI, UAT

#280 transcript css change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
Labels: UI

#269 Task notice pdf changes
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend, QA

#285 exit hearing button styling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
Labels: UI

#283 Summon modal fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI, UAT

#288 Uat develop deploy
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
Labels: UI

#287 added autoCreateFlage to true
  common/egov-idgen/src/main/java/org/egov/id/service/IdGenerationService.java
Labels: Backend

#284 courtid added in hearing search
  api_specifications/hearing-api-0.1.0.yaml
  backend/hearing/src/main/java/org/pucar/dristi/repository/querybuilder/HearingQueryBuilder.java
  backend/hearing/src/main/java/org/pucar/dristi/web/models/HearingCriteria.java
Labels: Backend

#290 court staff pending-task of summon fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#291 updated order number format
  backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java
  backend/order/src/main/java/org/pucar/dristi/web/models/Order.java
Labels: Backend

#292 Develop deploy uat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#294 pick scheduler service from develop
  backend/scheduler-svc/src/main/java/digit/service/CalendarService.java
  backend/scheduler-svc/src/main/java/digit/task/RequestOptOutScheduleTask.java
Labels: Backend, UAT

#295 changes to download case file in correction modal, and add check on l…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CorrectionsSubmitModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI, UAT

#299 uat pending task close, css changes, FSO filter fix
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#300 Develop 6 deploy uat
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CorrectionsSubmitModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#302 FSO Filed filter bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
Labels: UI

#304 join a case last name fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI, UAT

#307 dristi case pdf changes migration for develop
  backend/dristi-case-pdf/config/config.js
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/fileService.js
  backend/dristi-case-pdf/service/pdfService.js
Labels: Backend, Develop

#310 place, additional comments, state in order pdfs
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
Labels: UI

#312 localization in withdrawal reason
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js
Labels: UI

#306 Removal Of Download All Link and Invalid name fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: bug, UI, UAT

#308 dristi case pdf changes migration for uat
  backend/dristi-case-pdf/config/config.js
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/fileService.js
  backend/dristi-case-pdf/service/pdfService.js
Labels: Backend, UAT

#309 dristi case pdf changes migration
  backend/dristi-case-pdf/config/config.js
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/fileService.js
  backend/dristi-case-pdf/service/pdfService.js
Labels: Backend, QA

#314 added application number
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/util/IdgenUtil.java
  backend/application/src/main/java/org/pucar/dristi/web/models/IdGenerationRequest.java
  backend/application/src/main/java/org/pucar/dristi/web/models/IdGenerationResponse.java
  backend/application/src/main/java/org/pucar/dristi/web/models/IdRequest.java
  backend/application/src/main/java/org/pucar/dristi/web/models/IdResponse.java
  backend/application/src/main/resources/application.properties
Labels: Backend

#216 raise-application bug
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: bug, UI

#321 Last name in view case , generate order.
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
Labels: UI, UAT

#325 document owner and visibility fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: UI

#326 Develop deploy from uat 23
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
Labels: UI

#327 remove repeated code
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#329 fix summons document issue.
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/java/digit/util/CaseManagementUtil.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/service/SummonsServiceTest.java
  backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend, UAT

#333 added caseType field and table
  backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseRowMapper.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CourtCase.java
  backend/case/src/main/resources/db/migration/main/V20240921110535__case__ddl.sql
  backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilderTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseRowMapperTest.java
Labels: Backend

#335 Sbi epay changes for multi account handling
  backend/sbi-backend/src/main/java/org/egov/sbi/model/AmountDetails.java
  backend/sbi-backend/src/main/java/org/egov/sbi/model/TransactionDetails.java
  backend/sbi-backend/src/main/java/org/egov/sbi/repository/TransactionDetailsQueryBuilder.java
  backend/sbi-backend/src/main/java/org/egov/sbi/repository/TransactionDetailsRowMapper.java
  backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java
  backend/sbi-backend/src/main/resources/db/migration/main/V20240923152900__sbi_backend_ddl
Labels: Backend, QA

#334 Sbi epay changes for multi account handling
  backend/sbi-backend/src/main/java/org/egov/sbi/model/AmountDetails.java
  backend/sbi-backend/src/main/java/org/egov/sbi/model/TransactionDetails.java
  backend/sbi-backend/src/main/java/org/egov/sbi/repository/TransactionDetailsQueryBuilder.java
  backend/sbi-backend/src/main/java/org/egov/sbi/repository/TransactionDetailsRowMapper.java
  backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java
  backend/sbi-backend/src/main/resources/db/migration/main/V20240923152900__sbi_backend_ddl
Labels: Backend, Develop

#274 not letting efile if generate pdf fails .
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI, UAT

#330 [UAT bug 1728]: Accused Name not filled in, in Join a Case Screen
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI, UAT

#341 updated evidence numbering generation
  backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java
  backend/evidence/src/test/java/org/pucar/dristi/enrichment/EvidenceEnrichmentTest.java
Labels: Backend

#345 scrutiny checklist
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#349 registration request break fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetAdvocateClerk.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#350 auto filling address using google live location disabled for accused …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
Labels: UI

#353 Offline App Payment
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/index.js
Labels: UI, UAT

#278 removed validation for summon
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/SummonCalculationCriteria.java
Labels: Backend, Develop

#348 updated worlflow definition
  docs/hearing/workflow/hearing-workflowConfig.json
  docs/task/workflow/task-workflowConfig.json
  docs/task/workflow/workflowConfig-notice.json
  docs/task/workflow/workflowConfig-summon.json
Labels: Backend

#359 develop payment-calculator changes to uat
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/CaseFeeCalculationService.java
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/EFillingCalculationCriteria.java
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/web/models/SummonCalculationCriteria.java
  backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/CaseFeeCalculationServiceTest.java
Labels: Backend, UAT

#364 uat pending task create for all summon type and respective changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
Labels: UI

#368 Uat bug 1725 fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
Labels: UI

#363 Confirm attendace in summon
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#357 updated evidence number based on source type
  backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java
  backend/evidence/src/test/java/org/pucar/dristi/enrichment/EvidenceEnrichmentTest.java
Labels: Backend

#367 Case hearing payload fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
Labels: UI

#375 added court name, place, state in config
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/adrCaseReferral.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
  utilities/dristi-pdf/src/orderHandlers/caseTransfer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderSection202crpc.js
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
  utilities/dristi-pdf/src/routes/order.js
Labels: UI, UAT

#376 summons address fix in create task
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#379 Enabling fields transfer order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI, UAT

#389 migrated changes regarding courtname and place from uat to develop
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/adrCaseReferral.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
  utilities/dristi-pdf/src/orderHandlers/caseTransfer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderSection202crpc.js
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
  utilities/dristi-pdf/src/routes/order.js
Labels: UI

#391 Updated court room name, judge name and judge designation
  utilities/dristi-pdf/src/config.js
Labels: UI

#385 Develop demo changes bnss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI, Develop

#395 Analytics payment type fix
  backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/analytics/src/main/java/org/pucar/dristi/util/BillingUtil.java
  backend/analytics/src/test/java/org/pucar/dristi/util/BillingUtilTest.java
Labels: bug, Backend, Develop

#386 close hearing changes after admitting a case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#401 removed min size application and duplicate workflow
  backend/application/src/main/java/org/pucar/dristi/web/models/Application.java
  docs/Advocate/worfkow/userregistration-workflowConfig.json
Labels: Backend

#392 Static causelist
  backend/scheduler-svc/causelist-document-persister.yml
  backend/scheduler-svc/causelist-persister.yml
  backend/scheduler-svc/src/main/java/digit/config/Configuration.java
  backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
  backend/scheduler-svc/src/main/java/digit/repository/CauseListRepository.java
  backend/scheduler-svc/src/main/java/digit/repository/querybuilder/CauseListQueryBuilder.java
  backend/scheduler-svc/src/main/java/digit/repository/rowmapper/CaseTypeRowMapper.java
  backend/scheduler-svc/src/main/java/digit/repository/rowmapper/CauseListRowMapper.java
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
  backend/scheduler-svc/src/main/java/digit/service/ReScheduleHearingService.java
  backend/scheduler-svc/src/main/java/digit/util/ApplicationUtil.java
  backend/scheduler-svc/src/main/java/digit/util/CaseUtil.java
  backend/scheduler-svc/src/main/java/digit/util/FileStoreUtil.java
  backend/scheduler-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/scheduler-svc/src/main/java/digit/web/models/AdvocateMapping.java
  backend/scheduler-svc/src/main/java/digit/web/models/ApplicationCriteria.java
  backend/scheduler-svc/src/main/java/digit/web/models/ApplicationRequest.java
  backend/scheduler-svc/src/main/java/digit/web/models/CaseType.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseList.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseListPdf.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseListSearchCriteria.java
  backend/scheduler-svc/src/main/java/digit/web/models/MdmsHearing.java
  backend/scheduler-svc/src/main/java/digit/web/models/Party.java
  backend/scheduler-svc/src/main/java/digit/web/models/SlotList.java
  backend/scheduler-svc/src/main/java/digit/web/models/SlotRequest.java
  backend/scheduler-svc/src/main/java/digit/web/models/hearing/HearingSearchCriteria.java
  backend/scheduler-svc/src/main/resources/application.properties
  backend/scheduler-svc/src/main/resources/db/migration/main/V20240923143000__causelist_ddl.sql
  backend/scheduler-svc/src/main/resources/db/migration/main/V20240923200900__causelist_ddl.sql
  backend/scheduler-svc/src/main/resources/db/migration/main/V20240926163300__causelist_ddl.sql
  backend/scheduler-svc/src/test/java/digit/repository/querybuilder/CauseListQueryBuilderTest.java
  backend/scheduler-svc/src/test/java/digit/repository/rowmapper/CauseListRowMapperTest.java
  backend/scheduler-svc/src/test/java/digit/service/CauseListServiceTest.java
  backend/scheduler-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend

#404 bnss and pending task fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#393 case pdf decryption changes
  backend/case/src/main/java/org/pucar/dristi/service/CasePdfService.java
Labels: Backend, Develop

#388 task warrant demand generation for police
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/service/DemandService.java
  backend/summons-svc/src/main/java/digit/web/models/ChannelName.java
  backend/summons-svc/src/main/java/digit/web/models/SummonCalculationCriteria.java
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend, Develop

#403 handle task-notice document fix.
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/NoticeDetails.java
  backend/summons-svc/src/main/java/digit/web/models/TaskDetails.java
  backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend, Develop

#405 setting default long, lat but empty address fields for respondent
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
Labels: UI

#414 fix summon and notice workflow changes.
  backend/dristi-case-pdf/config/config.js
  backend/dristi-case-pdf/controller/caseController.js
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/enrichment/SummonsDeliveryEnrichment.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/resources/application.properties
  backend/task/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
  backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
Labels: Backend, Develop

#417 hard coded the court name
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
Labels: UI

#424 pdf service handle case where qr code is a url
  common/pdf-service/src/index.js
Labels: Develop

#422 Removal of hardcoded Value in CRM and Duplicate Validation Check in B…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/ReviewCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI, UAT

#428 Payment breakdown changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useRepondentPincodeDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useSummonsPaymentBreakUp.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#429 FSO reassigning issue fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomRadioInfoComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#420 Sbi webpage read response properly
  backend/sbi-backend/src/main/java/org/egov/sbi/model/BrowserDetails.java
  backend/sbi-webpage/app.js
Labels: Backend, Develop

#443 Uat to develop UI 2
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
Labels: UI

#445 don't stringify payload if already a string
  backend/sbi-webpage/app.js
Labels: Backend, Develop

#449 Epoc Time Converion
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/index.js
Labels: bug, UI

#456 Sbi payment status success page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
Labels: UI

#458 Bnss court summon
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#460 copy text div changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCopyTextDiv.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSubmitModal.js
Labels: UI

#462 draft in progress pending task for notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#459 fixed google map issue
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/PopUp.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
Labels: UI

#465 Epoc Time Conversion
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/index.js
Labels: UI

#466 bnss bug fixes, draft in progress fix, copy text div changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCopyTextDiv.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSubmitModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#469 updated application number format
  backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java
Labels: Backend

#472 Causelist generate
  backend/scheduler-svc/causelist-document-persister.yml
  backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
  backend/scheduler-svc/src/main/java/digit/repository/querybuilder/CauseListQueryBuilder.java
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
  backend/scheduler-svc/src/main/java/digit/web/controllers/CauseListApiController.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseListPdf.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseListSearchRequest.java
  backend/scheduler-svc/src/main/resources/db/migration/main/V20240930143000__causelist_ddl.sql
Labels: Backend

#474 cause list changes, warrant details fix in court staff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#470 added filing number as field and hearing date string proper formatting
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
Labels: Backend, Develop

#480 Submission button admission hearing fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#468 Fix for payment issue from pending task for e-filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
Labels: UI

#477 advocate variable name correction
  backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
  backend/scheduler-svc/src/main/java/digit/web/controllers/CauseListApiController.java
Labels: Backend
