Repository pucardotorg/dristi-solutions, pull requests merged in 2024-11, with the labels that each got.

#820 adding courtId only if case is in draft stage
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#819 adding courtId only if not in draft stage
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#821 Id Proof, vakalatnama mark error and id proof display in advocate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#822 Upload ID Proof field is to accept the jpeg format
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#823 Added one user role to update the workflow.
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/service/SummonsServiceTest.java
Labels: Backend

#811 [2113, 2303]: restricting actions and pending tasks viewed for court room manager
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/HearingOverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
Labels: UI

#827 [bug 2152] [Security]: Filestore APIs should have authentication
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useDownloadCasePdf.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js
Labels: UI

#830 added info note box for cause list download btn
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
Labels: UI

#829 added info note box for cause list download btn
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
Labels: UI

#828 dependent fields, mark same error in scrutiny
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
Labels: UI

#799 enable reverification sbi api.
  backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java
Labels: Backend

#832 Send purpose of hearing to show in order pdf
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
Labels: UI

#834 Change of key for case search criteria
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#836 updated hard coded string with localized codes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#835 updated hard coded string with localized codes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#837 updated link for Section 138 link in E Filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#838 updated link for Section 138 link in E Filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#846 Change in config to update the text in file upload and to allow vario…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadFiles.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#845 Change in config to update the text in file upload and to allow vario…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadFiles.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#844 changed conditions on toast messages for hearing reschedule orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#843 changed conditions on toast messages for hearing reschedule orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#839 [BUG 2352]: [DPG-DEV | Schedule Hearing button should be disabled in Court Staff user
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#850 Scrutiny checklist sync up
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
Labels: UI

#852 added latest CSS style-sheet link
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/public/index.html
Labels: UI

#849 allow png in Upload id in e-fling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/component.js
Labels: UI

#862 CASE_CREATOR & CASE_EDITOR Roles are not mandaotry for Nyay-Mitra
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#866 fixed encryption issue
  backend/case/src/main/java/org/pucar/dristi/service/CasePdfService.java
Labels: Backend

#855 Conditional - Action column in summons, notice, warrants payment
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#854 Conditional - Action column in summons, notice, warrants payment
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#868 hide map functionality and autofilling of details in location
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#869 hide map functionality and autofilling of details in location
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#874 fetching hearing with scheduled/opt out state
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#873 fetching hearing with scheduled/opt out state
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#876 Show Option to Reschedule Hearing for Schedule Only
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#877 Show Option to Reschedule Hearing for Schedule Only
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#879 disabling all button in evidence modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#878 disabling all button in evidence modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#880 removed flag from advocateIdProof
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
Labels: UI

#881 removed flag from advocateIdProof
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
Labels: UI

#891 showing advocate details page only if advocate_viwer role is present
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#890 showing advocate details page only if advocate_viwer role is present
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#892 updated hard coded strings
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSortComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/PaymentInbox.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
Labels: UI

#899 Updated end point in advocate details page (#865) (#895)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/ApplicationAwaitingPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#897 sending null in createdDate in GenerateOrder
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/SummaryModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/ReschedulingPurpose.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersHome.js
Labels: UI

#896 sending null in createdDate in GenerateOrder
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/SummaryModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/ReschedulingPurpose.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersHome.js
Labels: UI

#900 Some words are missing in Malayalam in Judge login
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#901 Some words are missing in Malayalam in Judge login
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#904 removed forgot password route
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
Labels: UI

#910 Case dependecy remove from nayamitra payment page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#906 in orders tab createdTime -> createdDate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
Labels: UI

#907 in orders tab createdTime -> createdDate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
Labels: UI

#911 Localization [some words are missing in Malayalam] in efiling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomDetailsCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/Response.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/HearingSideCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#912 Localization [some words are missing in Malayalam] in efiling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomDetailsCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/Response.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/HearingSideCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#914 Case dependecy remove from nayamitra payment page (#910)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#915 Case dependecy remove from nayamitra payment page (#910)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#925 Adding new roles to litigant, advocate_clerk and advocat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#902 removed forgot password route link
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
Labels: UI

#913 bug removed frontend route link
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/index.js
Labels: UI

#928 added some additionalDetails field value in demand object.
  backend/summons-svc/src/main/java/digit/service/DemandService.java
  backend/summons-svc/src/main/java/digit/web/models/DemandAdditionalDetails.java
Labels: Backend

#875 registration date should be null instead of zero
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseRowMapper.java
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapper.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseRowMapperTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapperTest.java
Labels: bug, Backend

#908 replacing with otp component
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OTPInput.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
Labels: UI

#929 Bug 1228 develop
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OTPInput.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
Labels: UI

#864 creating delay condonation application while registering the case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#926 Adding new roles to litigant, advocate_clerk and advocate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#930 registration date should be null instead of zero
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseRowMapper.java
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapper.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseRowMapperTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapperTest.java
Labels: Backend

#887 Enhance 2279 : enrich created date when order is published
  backend/order/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java
  backend/order/src/main/java/org/pucar/dristi/service/OrderRegistrationService.java
Labels: Backend

#921 validations for currupt files
  common/egov-filestore/src/main/java/org/egov/filestore/config/FileStoreConfig.java
  common/egov-filestore/src/main/java/org/egov/filestore/validator/StorageValidator.java
  common/egov-filestore/src/main/resources/application.properties
Labels: Backend

#937 Adding malayam fo default mapping
  common/pdf-service/src/index.js
Labels: UI

#938 Adding malayam fo default mapping
  common/pdf-service/src/index.js
Labels: UI

#940 updated nyay mitra roles
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
Labels: UI

#943 added applicationCmpnumber field and updated application number to ha…
  backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilder.java
  backend/application/src/main/java/org/pucar/dristi/repository/rowMapper/ApplicationRowMapper.java
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/main/java/org/pucar/dristi/web/models/Application.java
  backend/application/src/main/resources/db/migration/main/V20241114110535__application__ddl.sql
  backend/application/src/test/java/org/pucar/dristi/enrichment/ApplicationEnrichmentTest.java
  backend/application/src/test/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilderTest.java
Labels: Backend

#948 added some regex to remove "" from config String
  common/pdf-service/src/index.js
Labels: UI

#951 fix case registration validation issue
  backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java
Labels: Backend

#949 search enabled based on applicationCmpnumber
  api_specifications/application-api-0.1.0.yaml
  backend/application/src/main/java/org/pucar/dristi/repository/queryBuilder/ApplicationQueryBuilder.java
  backend/application/src/main/java/org/pucar/dristi/web/models/ApplicationCriteria.java
Labels: Backend

#952 changing from application to applicationCMP number
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
Labels: UI

#687 Feature sequential sign
  backend/e-sign-svc/.gitignore
  backend/e-sign-svc/esign-persister.yml
  backend/e-sign-svc/pom.xml
  backend/e-sign-svc/src/main/java/org/drishti/esign/Main.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/cipher/Decryption.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/cipher/Encryption.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/config/Configuration.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/config/ServiceConstants.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/kafka/Producer.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/repository/EsignRequestRepository.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/repository/rowmapper/EsignRowMapper.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/service/ESignService.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/service/PdfEmbedder.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/service/XmlSigning.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/util/FileStoreUtil.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/util/TextLocationFinder.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/web/controllers/EsignApiController.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/web/models/Coordinate.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/web/models/ESignParameter.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/web/models/SignDocParameter.java
  backend/e-sign-svc/src/main/resources/application.properties
  backend/e-sign-svc/src/main/resources/db/Dockerfile
  backend/e-sign-svc/src/main/resources/db/migration/main/V20241017153200__esign__ddl.sql
  backend/e-sign-svc/src/main/resources/db/migration/main/V20241018135800__esign_audit__ddl.sql
  backend/e-sign-svc/src/test/java/org/drishti/esign/service/ESignServiceTest.java
  backend/e-sign-svc/src/test/java/org/drishti/esign/service/PdfEmbedderTest.java
  backend/e-sign-svc/src/test/java/org/drishti/esign/service/XmlSigningTest.java
  backend/e-sign-svc/src/test/java/org/drishti/esign/util/FileStoreUtilTest.java
  backend/e-sign-svc/src/test/java/org/drishti/esign/web/controllers/EsignApiControllerTest.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/config/ServiceConstants.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/repository/ServiceRequestRepository.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/service/InterceptorService.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/util/FileStoreUtil.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/web/controllers/InterceptorApiController.java
  backend/esign-interceptor/src/main/java/com/pucar/drishti/web/models/SignDocParameter.java
  backend/esign-interceptor/src/test/java/com/pucar/drishti/service/InterceptorServiceTest.java
  backend/esign-interceptor/src/test/java/com/pucar/drishti/util/FileStoreUtilTest.java
  backend/esign-interceptor/src/test/java/com/pucar/drishti/web/controllers/EsignApiControllerTest.java
Labels: Backend, Develop

#944 enhance existing end point to support generic task creation
  backend/task/src/main/java/org/pucar/dristi/annotation/CombineRequiredFields.java
  backend/task/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/task/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/task/src/main/java/org/pucar/dristi/repository/TaskRepository.java
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskQueryBuilder.java
  backend/task/src/main/java/org/pucar/dristi/repository/rowmapper/TaskRowMapper.java
  backend/task/src/main/java/org/pucar/dristi/util/CaseUtil.java
  backend/task/src/main/java/org/pucar/dristi/validators/CombineValidator.java
  backend/task/src/main/java/org/pucar/dristi/validators/TaskRegistrationValidator.java
  backend/task/src/main/java/org/pucar/dristi/web/models/AssignedTo.java
  backend/task/src/main/java/org/pucar/dristi/web/models/Task.java
  backend/task/src/main/java/org/pucar/dristi/web/models/TaskCriteria.java
  backend/task/src/main/java/org/pucar/dristi/web/models/TaskExists.java
  backend/task/src/main/resources/application.properties
  backend/task/src/main/resources/db/migration/main/V20241112155600__task__ddl.sql
  backend/task/src/test/java/org/pucar/dristi/repository/TaskRepositoryTest.java
  backend/task/src/test/java/org/pucar/dristi/repository/querybuilder/TaskQueryBuilderTest.java
Labels: Backend

#959 fixed roles acc. to new role action mapping
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#960 Define proper error page and error message
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
Labels: UI

#963 Bug 2411 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#961 Define proper error page and error message
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
Labels: UI

#962 updated css for advocate continue button styling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#964 allow apostrophe in object for case pdf change
  common/pdf-service/src/utils/directMapping.js
Labels: UI

#954 Join case new enhancement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
Labels: UI

#957 [Bug 2397]: Nyaymitra user is not able to download file, throwing authentication error hotfix 0.5
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js
Labels: UI

#966 Join case new enhancement to release
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
Labels: UI

#969 throwing appropriate error whenever file is corrupted
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/service/fileService.js
  backend/dristi-case-pdf/util/errorUtils.js
Labels: UI

#972 Bug 2426
  backend/task/src/main/java/org/pucar/dristi/enrichment/TaskRegistrationEnrichment.java
  backend/task/src/main/java/org/pucar/dristi/util/CaseUtil.java
  backend/task/src/main/java/org/pucar/dristi/validators/TaskRegistrationValidator.java
  backend/task/src/main/java/org/pucar/dristi/web/models/AssignedTo.java
  backend/task/src/main/resources/application.properties
Labels: bug, Backend

#967 Bug 2032 analytics
  backend/analytics/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/analytics/src/main/java/org/pucar/dristi/util/IndexerUtils.java
  backend/analytics/src/main/java/org/pucar/dristi/util/TaskUtil.java
  backend/analytics/src/main/java/org/pucar/dristi/web/models/PendingTaskType.java
  backend/analytics/src/test/java/org/pucar/dristi/util/IndexerUtilsTest.java
  backend/analytics/src/test/java/org/pucar/dristi/util/TaskUtilTest.java
  backend/analytics/src/test/java/org/pucar/dristi/web/models/PendingTaskTypeTest.java
Labels: Backend

#976 displaying error in upload signature when file limit exceeds
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadSignatureModal.js
Labels: UI

#975 displaying error in upload signature when file limit exceeds
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadSignatureModal.js
Labels: UI

#973 ocr bug fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#971 updated application state and skip causeList for delay condonation
  backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
Labels: Backend

#977 added await to creatependingtask function
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#979 localisation missing on judge and courtstaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#980 localisation missing on judge and courtstaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#984 adding owner in delay condonation and removing delay condonation from…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#989 complaint pdf endpoint changes
  backend/dristi-case-pdf/config/config.js
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/pdfService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#990 button unclickable resolved happening due to loacalisation missed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#991 Bug missed localisation dristi
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#974 No Pending task being created for Response
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#987 added a error msg when screen width is less than 900
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/App.js
Labels: UI

#988 added a error msg when screen width is less than 900
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/App.js
Labels: UI

#994 showing prev fso errors
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#995 showing prev fso errors
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#999 added array condition in datamapping, added empy documentList condition
  backend/dristi-case-pdf/service/caseService.js
  common/pdf-service/src/utils/directMapping.js
Labels: UI

#997 same day hearing joining bug fixed #1993
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#1000 Pending task closed fix feature #2032
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#1001 multi esign placeholder for pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
Labels: UI

#998 same day hearing joining bug fixed #1993
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#993 No Pending task being created for Response (#974)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1002 role action and workflow update
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#1005 removing temp testing variable
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#1007 Missed loaclisation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomInput.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectBulkInputs.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1008 Missed loaclisation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomInput.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectBulkInputs.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SignatureCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1009 Pending response bug fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js
Labels: UI

#1010 Pending response bug dev push
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#1017 APPLICATION_CREATOR to SUBMISSION_CREATOR
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
Labels: UI

#1021 Enhance 1964 position fix
  .github/workflows/Image-build-e-sign-svc.yaml
  backend/e-sign-svc/src/main/java/org/drishti/esign/util/TextLocationFinder.java
Labels: Backend

#1023 UI chnage for substage localisation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#1025 adding complaint pdf in documents
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#1028 case search not getting called first time fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1027 case search not getting called first time fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1024 Bug 2445
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1029 added auth token in header
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPaymentResponse.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentRes.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1030 added authtoken in header
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPaymentResponse.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentRes.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1033 Hot fix/0.5 for adding auth token in headers for filstore/ id api
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/RenderFileUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPaymentResponse.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentRes.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1036 Fixed redirection issue in courtstaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#1038 Fixed redirection issue in courtstaff (#1036)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#1039 Fixed redirection issue in courtstaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#1040 updated hard coded string court staff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#1042 view case pdf not shown in esign fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#1041 view case pdf not shown in esign fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#1043 updated pdf issue opening
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1044 updated pdf view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1046 updated pdf issue opening
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#1047 view case pdf not shown in esign fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#1056 changed docType of complaint pdf, added phone number for advocate, .join fix in pdf-service
  backend/dristi-case-pdf/service/caseService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#1057 added null check for complaint pdf
  backend/dristi-case-pdf/service/caseService.js
Labels: UI

#1059 Bug 1964 position fix
  backend/e-sign-svc/src/main/java/org/drishti/esign/service/PdfEmbedder.java
  backend/e-sign-svc/src/main/java/org/drishti/esign/util/TextLocationFinder.java
Labels: Backend

#1063 not loading potential errors when it's nth round of scrutiny
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
Labels: UI

#1064 not loading potential errors when it's nth round of scrutiny
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
Labels: UI

#1065 Bug 1974 develop
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
Labels: UI

#1070 taking first element for docs
  backend/dristi-case-pdf/service/caseService.js
Labels: UI

#1073 aading complainantIdProof in docs
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/fileService.js
Labels: UI

#1074 fixed bug #2174 and make error page responsive and enhance ui #2151
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorBoundaries.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#1066 added auth token in case print case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/authenticatedLink.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentPrintComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#1075 fixed bug #2174 and make error page responsive and enhance ui #2151
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorBoundaries.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ErrorComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#1072 added due date parameter
  api_specifications/task-api-0.1.0.yaml
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskQueryBuilder.java
  backend/task/src/main/java/org/pucar/dristi/repository/rowmapper/TaskRowMapper.java
  backend/task/src/main/java/org/pucar/dristi/web/models/Task.java
Labels: Backend

#1080 Fixed bug #2439 (Views of requests for Advocate clerk is blank)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js
Labels: UI
