Repository pucardotorg/dristi-solutions, pull requests merged in 2024-10, with the labels that each got.

#476 Generate pending task for respondent
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#489 Sending cmpNumber while creating and updating application and update …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#488 null handle for slotName
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
Labels: Backend

#492 getting filestoreid from localstorage
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#491 case filing number read year and number properly
  backend/dristi-case-pdf/controller/caseController.js
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
Labels: Backend, Develop

#494 creating draft in progress pending task after generating order notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
Labels: UI

#495 Efiling esign bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#496 Added extra check after completion of esign in orders and submission
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
Labels: UI, UAT

#497 added check on whether addresseDetails is object or a string
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI

#501 Uat bug fix nitish
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#502 continuosly enter button bug fixed, optional field for register respo…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/RegisterRespondentForm.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/resgisterRespondentConfig.js
Labels: UI

#508 change in task table search query
  backend/task/src/main/java/org/pucar/dristi/repository/TaskRepository.java
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
Labels: Backend

#481 fix task document fixes after courtstaff esign.
  backend/epost-tracker/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/epost-tracker/src/main/java/org/pucar/dristi/util/EpostUtil.java
  backend/epost-tracker/src/test/java/org/pucar/dristi/util/EpostUtilTest.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/config/ServiceConstants.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/enrichment/IcopsEnrichment.java
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/kafka/SummonsConsumer.java
  backend/summons-svc/src/main/java/digit/service/SummonsService.java
  backend/summons-svc/src/main/java/digit/util/CaseUtil.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/CaseCriteria.java
  backend/summons-svc/src/main/java/digit/web/models/CaseSearchRequest.java
  backend/summons-svc/src/main/java/digit/web/models/Order.java
  backend/summons-svc/src/main/java/digit/web/models/Pagination.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/service/SummonsServiceTest.java
  backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend, UAT

#511 hiding extension of submission deadline button
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#512 fix warrant changes based on new workflow.
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/java/digit/web/models/TaskDetails.java
  backend/summons-svc/src/main/java/digit/web/models/WarrantDetails.java
  backend/summons-svc/src/main/java/digit/web/models/WitnessDetails.java
  backend/summons-svc/src/main/resources/application.properties
  backend/task/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/task/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
  backend/task/src/main/java/org/pucar/dristi/service/TaskService.java
Labels: Backend, UAT

#514 logo change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LanguageSelection.js
Labels: UI

#524 bailableAmount property name fix and warrant action fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#523 updated application number format
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/main/resources/application.properties
Labels: Backend

#533 Order parties added
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#536 update test
  backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java
Labels: Backend

#525 round off to 2 decimal
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/util/SpeedPostUtil.java
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/util/TaskUtil.java
Labels: Backend

#546 1914 bug the close button is hidden behind the top bar
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
Labels: UI, UAT

#543 [#1645]: User Registration: Advocate API has /advocate/advocate in PATH
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/advocateSearchConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateNameDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantDummy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/DebtDummy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/ApplicationAwaitingPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/litigantHome/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  utilities/dristi-pdf/src/config.js
Labels: UI

#548 added documentType mdms validation
  backend/order/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/order/src/main/java/org/pucar/dristi/validators/OrderRegistrationValidator.java
  backend/order/src/main/resources/application.properties
  backend/order/src/test/java/org/pucar/dristi/validators/OrderRegistrationValidatorTest.java
Labels: Backend

#550 Bug FIx related to BAR registration number already registered message…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AdvocateDetailComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
Labels: UI, UAT

#537 [UAT 1892, QA 1876] google map, pincode related bug fix in accused's address details
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#553 sending partyName and partType inside parties
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#560 billSearch Boolean fix in SMS Payment Modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#555 Witness formdata fix
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/service/fileService.js
  backend/dristi-case-pdf/service/pdfService.js
Labels: Backend, UAT

#572 made changes for delay condonation to skip the workflow
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java
Labels: Backend

#575 UAT bugs 1931, 1939, 1948, 1952 fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#577 payload changes in court staff for api "/task/v1/table/search" and Fix for hiding top bar when modal is open.
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI, UAT

#578 Case PDF Preview before signing changes in reviewCase
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#583 Scrutiny Bug fix - hiding flag icon if Document uploaded in prayer and sworn
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#589 css overlapping changes and localization in header changes in view case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
Labels: UI, UAT

#569 delay Condonation api added
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#594 case-pdf Bugs fix (1941)
  backend/dristi-case-pdf/service/caseService.js
Labels: Backend

#598 bug fixed for parties for certain order types
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#602 removing aadhar auto verify button in e filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
Labels: UI, UAT

#573 application number enriching by cmp
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/util/CaseUtil.java
  backend/application/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
  backend/application/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
  backend/application/src/main/resources/application.properties
  backend/application/src/test/java/org/pucar/dristi/util/CaseUtilTest.java
Labels: Backend

#604 Replace 'Issue Order' with 'Issue Notice'
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
Labels: bug, UI

#609 Option to close pop up
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: enhancement, UI

#613 efiling form edits and validations
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/efilingDocumentKeyAndTypeMapping.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#610 change in case search query
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
Labels: Backend

#616 unknown respondent issue and partyName breakage fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI, UAT

#617 save deposition button disable fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
Labels: UI, UAT

#619 summons and notice pdf issue.
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/test/java/digit/util/PdfServiceUtilTest.java
Labels: Backend, QA

#620 Changed Esigning Page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/index.js
Labels: UI

#629 schedule hearing break fix, sending docSubType in summons and notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js
Labels: UI, UAT

#606 application number enrichment by cmp number on submission approval
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/util/CaseUtil.java
  backend/application/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
  backend/application/src/main/java/org/pucar/dristi/web/models/CaseSearchRequest.java
  backend/application/src/main/resources/application.properties
  backend/application/src/test/java/org/pucar/dristi/util/CaseUtilTest.java
Labels: Backend

#631 sorting of task
  backend/task/src/main/java/org/pucar/dristi/repository/TaskRepository.java
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
Labels: Backend

#622 number generation for evidence implementation
  backend/evidence/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
  backend/evidence/src/main/resources/application.properties
  backend/evidence/src/test/java/org/pucar/dristi/enrichment/EvidenceEnrichmentTest.java
Labels: Backend

#644 parties page break fix in view case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI, UAT

#643 sorting correct for task table search
  backend/task/src/main/java/org/pucar/dristi/repository/TaskRepository.java
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
Labels: Backend

#626 Feature case summary api
  backend/case/src/main/java/org/pucar/dristi/annotation/OneOf.java
  backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/case/src/main/java/org/pucar/dristi/repository/CaseRepository.java
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseSummaryQueryBuilder.java
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapper.java
  backend/case/src/main/java/org/pucar/dristi/scheduling/CronJobScheduler.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
  backend/case/src/main/java/org/pucar/dristi/validators/OneOfValidator.java
  backend/case/src/main/java/org/pucar/dristi/web/controllers/CaseApiController.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSearchCriteria.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSummary.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSummaryRequest.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSummaryResponse.java
  backend/case/src/main/java/org/pucar/dristi/web/models/Judge.java
  backend/case/src/main/java/org/pucar/dristi/web/models/Pagination.java
  backend/case/src/main/java/org/pucar/dristi/web/models/PartySummary.java
  backend/case/src/main/java/org/pucar/dristi/web/models/RepresentativeSummary.java
  backend/case/src/test/java/org/pucar/dristi/repository/CaseRepositoryTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilderTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseSummaryQueryBuilderTest.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapperTest.java
  backend/case/src/test/java/org/pucar/dristi/service/CaseServiceTest.java
  backend/case/src/test/java/org/pucar/dristi/validators/OneOfValidatorTest.java
  backend/case/src/test/java/org/pucar/dristi/web/controllers/CaseApiControllerTest.java
Labels: Backend, Develop

#625 Feature 1926 e filing case locking
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#639 bugs -2028 treasury backend enrichment class
  backend/treasury-backend/src/main/java/org/egov/eTreasury/config/PaymentConfiguration.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/ChallanData.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/HeadDetails.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/service/PaymentService.java
  backend/treasury-backend/src/main/resources/application.properties
Labels: Backend, UAT

#646 new Esign flow Completion
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#624 Localization missing in OCR error
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
Labels: UI

#637 case workflow updated for new changes
  docs/Case/workflow/case-workflow.json
Labels: Backend

#648 bugs -2040 collection service added a flag for fractional payment
  common/collection-services/src/main/java/org/egov/collection/config/ApplicationProperties.java
  common/collection-services/src/main/java/org/egov/collection/util/PaymentValidator.java
  common/collection-services/src/main/java/org/egov/collection/util/Utils.java
  common/collection-services/src/main/resources/application.properties
Labels: Backend, UAT

#645 using filing number inplace of cnr for idgen numbers
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/web/models/Application.java
  backend/application/src/test/java/org/pucar/dristi/enrichment/ApplicationEnrichmentTest.java
  backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java
  backend/evidence/src/test/java/org/pucar/dristi/enrichment/EvidenceEnrichmentTest.java
  backend/hearing/src/main/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichment.java
  backend/hearing/src/test/java/org/pucar/dristi/enrichment/HearingRegistrationEnrichmentTest.java
  backend/order/src/main/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichment.java
  backend/order/src/main/java/org/pucar/dristi/web/models/Order.java
  backend/order/src/test/java/org/pucar/dristi/enrichment/OrderRegistrationEnrichmentTest.java
  backend/task/src/main/java/org/pucar/dristi/enrichment/TaskRegistrationEnrichment.java
  backend/task/src/test/java/org/pucar/dristi/enrichment/TaskRegistrationEnrichmentTest.java
Labels: Backend

#651 bug related to redirection and removal of hardCoded fileID
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#653 resolved bug 2044, updated where condition logic
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseSummaryQueryBuilder.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSearchCriteria.java
Labels: bug, Backend

#656 Completion Of Scrutiny-flow
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#657 added missing false update in summary query builder
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseSummaryQueryBuilder.java
Labels: Backend

#658 e-filing new form edits and validations
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#664 resolved conflict for application
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/test/java/org/pucar/dristi/util/CaseUtilTest.java
Labels: Backend

#665 resolved missing conflict for application
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
Labels: Backend

#672 case stage getting updated based on action only not status
  backend/analytics/src/main/java/org/pucar/dristi/util/CaseOverallStatusUtil.java
  backend/analytics/src/test/java/org/pucar/dristi/util/CaseOverallStatusUtilTest.java
Labels: Backend

#661 Uat v0.3 to develop
  backend/ocr-service/ocr-persister.yml
  backend/ocr-service/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/ocr-service/src/main/java/org/pucar/dristi/repository/rowMapper/OcrRowMapper.java
  backend/ocr-service/src/main/java/org/pucar/dristi/service/Service.java
  backend/ocr-service/src/main/java/org/pucar/dristi/web/model/Ocr.java
  backend/ocr-service/src/main/resources/db/migration/main/V20241011201700__ocr_code_ddl.sql
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/config/PaymentConfiguration.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/ChallanData.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/HeadDetails.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/service/PaymentService.java
  backend/treasury-backend/src/main/resources/application.properties
  common/collection-services/src/main/java/org/egov/collection/config/ApplicationProperties.java
  common/collection-services/src/main/java/org/egov/collection/util/PaymentValidator.java
  common/collection-services/src/main/java/org/egov/collection/util/Utils.java
  common/collection-services/src/main/resources/application.properties
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/Home/LanguageSelection.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js
Labels: Develop

#678 efiling config review changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#454 updated size of bill_id in table.
  backend/sbi-backend/src/main/resources/db/migration/main/V20240928092800__sbi_backend_ddl.sql
Labels: Backend, UAT

#677 online payment for all summons, notice, warrants
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/PaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
Labels: UI

#681 Fix to show correct amount for case in nyay mitra .Create demand and …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
Labels: UI

#682 Button text fix in add signature of review summon and notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#641 updated pom.xml according to code scan alerts
  .github/workflows/code-scanner.yaml
  backend/scheduler-svc/pom.xml
Labels: Backend, code scan

#635 updated pom.xml according to code scan alerts
  .github/workflows/code-scanner.yaml
  common/egov-hrms/pom.xml
Labels: Backend, code scan

#633 updated the pom.xml according to code scan alerts
  .github/workflows/code-scanner.yaml
  common/egov-idgen/pom.xml
Labels: Backend, code scan

#684 bug fixes in payment
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#686 e-filing complaint text area changes, sending accused and witness det…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#698 Order Status is wrong if box is closed in QA
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: bug, UI

#702 removed raise application button in overview, enable Complaint tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#703 removed raise application button in overview, enable Complaint tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#693 updated pom.xml according to scan code alerts
  common/inbox/pom.xml
Labels: Backend, code scan

#704 Add the cross button on the top right corner of the pop up screen for…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
Labels: bug, UI

#705 Bug #2078 #2130
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
Labels: UI

#701 [bug- 2142]: Internal Server Error while Order Signing (OPTOUT -> OPT_OUT)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/hearingWorkflow.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#706 CSS Issue in Submit button #1938
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
Labels: UI

#707 response submit button style fixed - bug #1938
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
Labels: UI

#676 Changes for issue Audit logs not reflecting in DB
  .github/workflows/code-scanner.yaml
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
  backend/case/src/main/java/org/pucar/dristi/service/PaymentUpdateService.java
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
  backend/hearing/src/main/java/org/pucar/dristi/service/HearingService.java
  backend/payment-calculator-svc/src/main/java/drishti/payment/calculator/service/PostalHubService.java
  backend/payment-calculator-svc/src/test/java/drishti/payment/calculator/service/PostalHubServiceTest.java
  backend/scheduler-svc/src/main/java/digit/Main.java
  backend/scheduler-svc/src/main/java/digit/config/Configuration.java
  backend/scheduler-svc/src/main/java/digit/config/ServiceConstants.java
  backend/scheduler-svc/src/main/java/digit/service/CalendarService.java
  backend/scheduler-svc/src/main/java/digit/service/CauseListService.java
  backend/scheduler-svc/src/main/java/digit/service/HearingService.java
  backend/scheduler-svc/src/main/java/digit/service/ReScheduleHearingService.java
  backend/scheduler-svc/src/main/java/digit/service/RescheduleRequestOptOutService.java
  backend/scheduler-svc/src/main/java/digit/service/UserService.java
  backend/scheduler-svc/src/main/java/digit/service/hearing/HearingProcessor.java
  backend/scheduler-svc/src/main/java/digit/service/hearing/OptOutProcessor.java
  backend/scheduler-svc/src/main/java/digit/task/RequestOptOutScheduleTask.java
  backend/scheduler-svc/src/main/java/digit/web/models/CauseListPdfRequest.java
  backend/scheduler-svc/src/test/java/digit/service/ReScheduleHearingServiceTest.java
  backend/scheduler-svc/src/test/java/digit/service/RescheduleRequestOptOutServiceTest.java
  backend/scheduler-svc/src/test/java/digit/service/hearing/OptOutProcessorTest.java
  backend/scheduler-svc/src/test/java/digit/task/RequestOptOutScheduleTaskTest.java
Labels: Backend

#712 bounced cheque to dishonored cheque
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/MakeSubmissionBailConfig.js
Labels: UI

#711 bounced cheque to dishonored cheque
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/MakeSubmissionBailConfig.js
Labels: UI

#713 Bugs 2143 2163 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#714 Bugs 2143 2163 release
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#719 added logger to test the status and action
  backend/analytics/src/main/java/org/pucar/dristi/util/CaseOverallStatusUtil.java
Labels: Backend

#721 Bug 2139 name null fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#720 Bug 2139 name null fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#724 added no witness added text, 150 age validation, typeOfEntity mandato…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#725 added no witness added text, 150 age validation, typeOfEntity mandato…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#726 added Individual condition in typeOfEntity
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#727 added Individual condition in typeOfEntity
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#729 Added scrutiny condition for send back for correct by judge
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#730 Added scrutiny condition for send back for correct by judge
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#739 Amount Paid shown is In-Correct in Court Staff User fixed and css issue fixed Bug 2136
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#740 Amount Paid shown is In-Correct in Court Staff User fixed and css issue fixed Bug 2136
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#741 Epost fees and recieved date In-correct fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ApplicationInfoComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
Labels: UI

#742 Epost fees and recieved date In-correct fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ApplicationInfoComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
Labels: UI

#743 fix sbi-transaction issue.
  backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java
Labels: Backend

#745 filingDAte not generated when advocate submits the case
  backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
Labels: Backend

#744 Bug opt out party in person
  backend/scheduler-svc/src/main/java/digit/config/Configuration.java
  backend/scheduler-svc/src/main/java/digit/service/ReScheduleHearingService.java
  backend/scheduler-svc/src/main/java/digit/service/hearing/OptOutProcessor.java
  backend/scheduler-svc/src/main/java/digit/util/AdvocateUtil.java
  backend/scheduler-svc/src/main/java/digit/util/CaseUtil.java
  backend/scheduler-svc/src/main/java/digit/web/models/Advocate.java
  backend/scheduler-svc/src/main/java/digit/web/models/AdvocateListResponse.java
  backend/scheduler-svc/src/main/java/digit/web/models/AdvocateSearchCriteria.java
  backend/scheduler-svc/src/main/java/digit/web/models/AdvocateSearchRequest.java
  backend/scheduler-svc/src/main/resources/application.properties
  backend/scheduler-svc/src/test/java/digit/service/hearing/OptOutProcessorTest.java
Labels: Backend

#716 Change to not show a case in judge if in draft state
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#717 Change to not show a case in judge if in draft state
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#748 fixed ui of otp modal and other minor ui fix, bug #1938
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/components/OtpComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/RegisterRespondentForm.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OTPInput.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
Labels: UI

#749 Localization changes in NextHearingCard
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
Labels: UI

#750 Localization changes in NextHearingCard
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
Labels: UI

#754 fix sbi-transaction issue.
  backend/sbi-backend/src/main/java/org/egov/sbi/service/PaymentService.java
Labels: Backend

#758 clearing out error when a party is chosen in summons/develop order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
Labels: UI

#756 summons,notice,warrant pdf fixes.
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
Labels: Backend

#759 case Tittle name update after Correction
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: bug, UI

#760 case Tittle name update after Correction
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: bug, UI

#764 create location-based-jurisdiction api.
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/controller/IcopsController.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/LocationBasedJurisdictionResponse.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/LocationRequest.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/service/IcopsService.java
  backend/icops_integration-kerala/src/test/java/com/egov/icops_integrationkerala/service/IcopsServiceTest.java
Labels: Backend

#761 generating cmp based application number on create
  backend/application/src/main/java/org/pucar/dristi/enrichment/ApplicationEnrichment.java
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/test/java/org/pucar/dristi/enrichment/ApplicationEnrichmentTest.java
  backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java
Labels: Backend

#771 added location-based api in security config.
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/config/SecurityConfig.java
Labels: Backend

#769 Summary Api enhancement
  .github/workflows/code-scanner.yaml
  api_specifications/case-api-0.1.0.yaml
  backend/case/src/main/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapper.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseSummary.java
  backend/case/src/test/java/org/pucar/dristi/repository/rowmapper/CaseSummaryRowMapperTest.java
Labels: Backend, Develop

#772 getting warrant executor name from icops.
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/config/ServiceConstants.java
  backend/summons-svc/src/main/java/digit/util/IcopsUtil.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/Location.java
  backend/summons-svc/src/main/java/digit/web/models/LocationBasedJurisdiction.java
  backend/summons-svc/src/main/java/digit/web/models/LocationBasedJurisdictionResponse.java
  backend/summons-svc/src/main/java/digit/web/models/LocationRequest.java
  backend/summons-svc/src/main/java/digit/web/models/PoliceStationDetails.java
  backend/summons-svc/src/main/resources/application.properties
  backend/summons-svc/src/test/java/digit/util/IcopsUtilTest.java
Labels: Backend

#777 bugFix on Reschedule Admission Hearing visible on reschedule
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#768 delay condonation implementation
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/application/src/main/java/org/pucar/dristi/service/WorkflowService.java
  backend/application/src/main/resources/application.properties
Labels: Backend

#780 addition of text in summon and notice modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI

#779 addition of text in summon and notice modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI

#778 bugFix on Reschedule Admission Hearing visible on reschedule
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#785 disable login otp as of now.
  common/user-otp/src/main/java/org/egov/domain/service/OtpService.java
  common/user-otp/src/main/resources/application.properties
Labels: Backend

#789 localized hard coded values in NyayMitra, sending coordinate in creat…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#790 localized hard coded values in NyayMitra, sending coordinate in creat…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#784 [feature 1998]: UATv0.3.3 | Add field in Order for Initiating Rescheduling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#787 [UAT 2000]: UATv0.3.3 | Option to View Transcript for Hearing not conducted yet
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#782 bug -2200 tool tip change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomErrorTooltip.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomNote.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadFiles.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ChequeDetails/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/advocateDetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/chequedetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/debtLiabilityConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/delayApplicationConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/prayerAndSwornConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/delayAppConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/AddParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#788 For all uploads across the product, the file types accepted should be…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadFiles.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/advocateDetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/chequedetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/debtLiabilityConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/delayApplicationConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/demandNoticeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/prayerAndSwornConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#791 added caseSearchText to filter based on cmpnumber,filingnumber,courtcasenuumber
  backend/case/src/main/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilder.java
  backend/case/src/main/java/org/pucar/dristi/web/models/CaseCriteria.java
  backend/case/src/test/java/org/pucar/dristi/repository/querybuilder/CaseQueryBuilderTest.java
Labels: Backend

#786 Show RPAD fullform in Order for Notice and Summons
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: bug, UI

#795 bug -2241 change in bar registration validation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#794 bug -2241 change in bar registration validation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#796 Scrutiny checklist update and enhancement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#803 addressed code rabbit comment
  backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
Labels: Backend

#801 bug -1979 css issue in file upload
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss
Labels: UI

#800 bug -1979 css issue in file upload
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customDragDrop.scss
Labels: UI

#804 new route to generate case complaint pdf
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/routes/caseRoutes.js
Labels: UI

#806 case search temporary fix in join case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#808 Feature 1991 - dropdown in join case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#805 marking error as error even if it's same as prev error
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI
