Repository pucardotorg/dristi-solutions, pull requests merged in 2024-12, with the labels that each got.

#1232 [BUG #2608]: [For faulty files Error message is not showing for only continue button ]
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#1233 Special characters are allowed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#1242 added ADVOCATE_APPLICATION_VIEWER for clerk, added ADVOCATE_VIEWER fo…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
Labels: UI

#1248 added benchclerk role to filter case
  backend/case/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/case/src/main/java/org/pucar/dristi/enrichment/CaseRegistrationEnrichment.java
Labels: Backend

#1249 Fix related to cache issue in Order Pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
Labels: UI

#1244 add cmpnumber in summon pdf
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend

#1254 added esign url to global config
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
Labels: UI

#1255 new workflow change for case e-filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#1261 add address in court configs
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend

#1264 change in date format
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
Labels: bug, Backend

#1265 changes for make filings and tab name change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
Labels: UI

#1183 New Open APIs for case search on landing page
  api_specifications/case-api-0.1.0.yaml
  api_specifications/open-api-0.1.0.yaml
  api_specifications/open-api-1.0.yaml
  backend/openapi/README.md
  backend/openapi/pom.xml
  backend/openapi/src/main/java/org/pucar/dristi/Main.java
  backend/openapi/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/openapi/src/main/java/org/pucar/dristi/config/MainConfiguration.java
  backend/openapi/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/openapi/src/main/java/org/pucar/dristi/kafka/Consumer.java
  backend/openapi/src/main/java/org/pucar/dristi/kafka/Producer.java
  backend/openapi/src/main/java/org/pucar/dristi/repository/ServiceRequestRepository.java
  backend/openapi/src/main/java/org/pucar/dristi/util/IdgenUtil.java
  backend/openapi/src/main/java/org/pucar/dristi/util/MdmsUtil.java
  backend/openapi/src/main/java/org/pucar/dristi/util/ResponseInfoFactory.java
  backend/openapi/src/main/java/org/pucar/dristi/util/UrlShortenerUtil.java
  backend/openapi/src/main/java/org/pucar/dristi/util/UserUtil.java
  backend/openapi/src/main/java/org/pucar/dristi/util/WorkflowUtil.java
  backend/openapi/src/main/java/org/pucar/dristi/web/controllers/OpenapiApiController.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/AllOfPaginationOrder.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/CaseListLineItem.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/CaseListResponse.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/CaseSummary.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/CaseSummaryResponse.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/Order.java
  backend/openapi/src/main/java/org/pucar/dristi/web/models/Pagination.java
  backend/openapi/src/main/resources/application.properties
  backend/openapi/src/test/java/org/pucar/dristi/TestConfiguration.java
  backend/openapi/src/test/java/org/pucar/dristi/web/controllers/OpenapiApiControllerTest.java
Labels: enhancement

#1267 enrich authentication with auth type
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/config/CustomAuthenticationProvider.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/model/ServiceCredential.java
  backend/icops_integration-kerala/src/main/java/com/egov/icops_integrationkerala/service/IcopsService.java
  backend/icops_integration-kerala/src/main/resources/application.properties
Labels: Backend

#1269 change the context path for icops
  backend/icops_integration-kerala/src/main/resources/application.properties
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend

#1275 handled multiple time calling docviewer files
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#1288 RequiredDocuments and Scrutiny Checklist url changes
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/downloadPdfWithLink.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#1289 added date validation for dateOfDispatch, it can't be before issuanceDate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#1291 modified the advocate display name format in nyaya mitra screen
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#1292 replaced + to & in epost payment screen
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
Labels: UI

#1103 download case pdf after registration
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#1298 Feature 2637 copy
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OwnerColumn.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/VoidSubmissionBody.js
Labels: UI

#1303 sending owner as name of the individual who is filing the application
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1302 Feature 2643 document submission
  backend/evidence/evidence-persister.yml
  backend/evidence/evidencewithoutworkflow-persister.yml
  backend/evidence/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/rowmapper/EvidenceRowMapper.java
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
  backend/evidence/src/main/java/org/pucar/dristi/service/WorkflowService.java
  backend/evidence/src/main/java/org/pucar/dristi/web/models/Artifact.java
  backend/evidence/src/main/resources/application.properties
  backend/evidence/src/main/resources/db/migration/main/V20241110144000__evidence__ddl.sql
  backend/evidence/src/test/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilderTest.java
  backend/evidence/src/test/java/org/pucar/dristi/repository/rowmapper/EvidenceRowMapperTest.java
  backend/evidence/src/test/java/org/pucar/dristi/service/EvidenceServiceTest.java
  backend/evidence/src/test/java/org/pucar/dristi/service/WorkflowServiceTest.java
  support/2643-mdms-data.json
  support/2643-mdms-schema.json
  support/2643-workflow.json
Labels: Backend

#1306 evidence api integrated and minor changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/VoidSubmissionBody.js
Labels: UI

#1307 registration req of advocate bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js
Labels: UI

#1317 Submit Documents Form and integration of apis
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/utils/joinCaseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/downloadPdfFromFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/submissionWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Button.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OwnerColumn.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/VoidSubmissionBody.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewDocumentSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentEsign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submitDocumentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/hooks/submissions/useSearchEvidenceService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/submissionDocumentsWorkflow.js
Labels: UI

#1315 decrypting data received from DB
  backend/case/src/main/java/org/pucar/dristi/service/CacheService.java
  backend/case/src/main/java/org/pucar/dristi/service/CaseService.java
  backend/case/src/main/java/org/pucar/dristi/validators/CaseRegistrationValidator.java
Labels: Backend

#1323 url change and next button disable condition change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/index.js
Labels: UI

#1324 Download submission fix in success modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1330 redirect fix on click of next in success modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1332 accused name and year fix in case bundle
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
Labels: UI

#1331 update to role of benchclerk to map the expected config
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#1329 mark void dev testing fix and reverted submission and documents renam…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/VoidSubmissionBody.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/HearingSideCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/DocumentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1338 Fix related to vakalat doc in case bundle
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
Labels: UI

#1335 showing error if respondentType not selected
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#1337 Fix css of void status, fix handle cancel issue and change hading for…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#1336 update the clerk and court staff config same as judge
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
Labels: UI

#1342 Optional Css Bug Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submitDocumentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1347 Feature 2695 increase comment size to 1000
  backend/order/src/main/resources/db/migration/main/V20241217113500__order__ddl.sql
Labels: Backend

#1341 remove the submitted status check
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
Labels: bug, Backend

#1350 error page fix, review modal open fix on empty fields
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1354 File type pdf name fix in case Bundle
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
Labels: UI

#1356 CourtName Fix
  utilities/dristi-pdf/src/config.js
Labels: UI

#1367 Bug Fix Related to Case Bundle POA Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
Labels: UI

#1366 filename is not visible for complainant id type and card is appending when advocate is adding complainant
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
Labels: UI

#1372 added USER_REGISTER in registration
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#1371 added USER_REGISTER in registration
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
Labels: UI

#1373 fix related to form Disablity
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1374 fix related to form Disablity
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#1377 update in evidence search
  backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/EvidenceRepository.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
  backend/evidence/src/main/java/org/pucar/dristi/web/models/EvidenceSearchCriteria.java
Labels: bug, Backend

#1380 created basic configs for bail acceptance and reject
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#1384 Application Heading Change
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
  utilities/dristi-pdf/src/config.js
Labels: UI

#1388 Order for bail config
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#1399 DCA Judge Screen Change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EndHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EvidenceHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#1398 Enhance application service to support updated workflow
  backend/application/src/main/java/org/pucar/dristi/config/Configuration.java
  backend/application/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/application/src/main/java/org/pucar/dristi/service/ApplicationService.java
  backend/application/src/main/java/org/pucar/dristi/service/WorkflowService.java
  backend/application/src/main/java/org/pucar/dristi/web/controllers/ApplicationApiController.java
  backend/application/src/main/java/org/pucar/dristi/web/models/ApplicationRequest.java
  backend/application/src/main/resources/application.properties
  backend/application/src/test/java/org/pucar/dristi/service/ApplicationServiceTest.java
  backend/application/src/test/java/org/pucar/dristi/web/controllers/ApplicationApiControllerTest.java
  docs/application/schemas/bail-doc.json
  support/2742-mdms-data.json
  support/2742-workflow.json
Labels: Backend

#1406 creating evidence after create application
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#1409 Feature 2728 2729 2730 new bail flow
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/submissionWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OwnerColumn.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/submissionWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/orderTypes.js
  support/2728-mdms-data.json5
  support/2729-mdms-data.json5
Labels: UI

#1410 Generic implimentation of Combination of Documents in Preview Screen related to order and its application
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetAllOrderApplicationRelatedDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
Labels: UI

#1411 pending task redirection and key changes in bail pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/orderHandlers/orderSetTermsOfBail.js
Labels: UI

#1415 fixed conditionOfBail pdf, showing RequestForBail after admission
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionDca.js
  utilities/dristi-pdf/src/orderHandlers/orderSetTermsOfBail.js
Labels: UI

#1417 order configs for dca, pdf key changes for dca and bail
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/2747-mdms-data.json
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionDca.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderSetTermsOfBail.js
Labels: UI

#1418 removed RefAppId from admitDismiss case order, pdf fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js
Labels: UI

#1419 noticeList in case admit pdf fix
  utilities/dristi-pdf/src/api.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionCase.js
Labels: UI

#1420 cron job for resetting seq number on jan 1 midnight
  common/egov-idgen/src/main/java/org/egov/id/config/Configuration.java
  common/egov-idgen/src/main/java/org/egov/id/config/SchedulerConfig.java
  common/egov-idgen/src/main/java/org/egov/id/config/SequenceResetService.java
  common/egov-idgen/src/main/resources/application.properties
Labels: Backend
