Repository pucardotorg/dristi-solutions, pull requests merged in 2025-03, with the labels that each got.

#2000 composite order impact related changes in other modules
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetAllOrderApplicationRelatedDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllOrderDrafts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2002 extractOrderNumber fun type validation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetAllOrderApplicationRelatedDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2001 [enhance-3229] - BoTD Visible Against Orders From Regular View
  frontend/micro-ui/web/micro-ui-internals/example/src/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useGetDiaryEntry.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
Labels: UI

#2005 change in application template related to changes in order form
  utilities/dristi-pdf/src/orderHandlers/orderSection202crpc.js
Labels: UI

#2008 [bug-3279] - remove info box, if all party joined
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2014 [bug-3222] - the dropdown opens below the screen fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
Labels: UI

#2015 [bug-3222] - the dropdown opens below the screen fixed, qa lowercase error
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllOrderDrafts.js
Labels: UI

#2017 [bug-3366] - hide botd from citizen screen
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
Labels: UI

#1999 Feature 3114
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/src/setupProxy.js
  frontend/pucar-ui/web/micro-ui-internals/example/src/setupProxy.js
  support/3114-mdms-schema.json
Labels: UI

#2024 [bug - 3370] - parties name should include both (comp and acc) fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2025 [bug - 3370] - parties name should include both (comp and acc) fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2029 [bug-fix] #3261 "Date Added" changed to "Date Issued" in Orders tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
Labels: UI

#2041 mandatory submission and set term bail combination in published order modal, BOTD fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2039 updated css for bulk reschedule
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/BulkReschedule.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
Labels: UI

#2049 Bug 3400
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2051 adding composite condition in admit/dismiss case pdf
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2048 [bug-fix] Updated Menu Modal with litigant/advocate and mobile number #3350
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/ProfileComponent.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
Labels: UI

#2057 added use effect to update calender view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
Labels: UI

#2053 [bug-fix] #3402 Fixed text appearing at bottom screen
  frontend/micro-ui/web/public/index.html
Labels: UI

#2060 enable add location button for judge send back
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2061 Transcript history of all hearings in view case - over view tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#2063 MAGISTRATE: Make transcript box as optional for the Magistrate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#2059 Feature 3231 : COMPOSITE ORDERS
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCopyTextDiv.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSucessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/CompositeOrdersErrorModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/MandatoryFieldsErrorModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrderItemDeleteModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2064 Bug conflicts
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/ProfileComponent.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/BulkReschedule.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/public/index.html
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2052 [bug-fix] #3355 - Exclude 15th day while calculating Date of Cause of Action fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#2070 dateOfHearing fix in Summon & Warrant, create task call for Intermediate fix, orderTitle localization fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllOrderDrafts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2080 [bug-fix] #3350 Default role removed from registration page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js
Labels: UI

#2078 [bug-fix] #3350 Default role removed from registration page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js
Labels: UI

#2082 radio button grey out color fix
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomRadioInfoComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUserTypeComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2089 redirect on pending task fix from evidenceModal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#2088 [bug-3379] Fixed minor bug of button disabled state
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
Labels: UI

#2093 updated payload for notification pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
Labels: UI

#2094 [Bug-3379-toMain] Fixed PoliceStation in reviewFileCase #3379
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationComponent.js
Labels: UI

#2092 updated payload for notification pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
Labels: UI

#2100 [PROD SUPPORT-3166] - pending task filter ehancement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/ProfileComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  support/3166-mdms-data.json
  support/3166-mdms-schema.json
Labels: UI

#2104 added calender css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2103 added calender css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2122 fix for FSO/Magistrate: Add Document button should be enabled every t…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2127 fix for auto populate fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2128 added order and notification tab
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/publishedNotificationModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#2142 Enhancement 3102 uat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectUploadDocWithName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2145 added hearing sorting based on caseNumber
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
Labels: UI

#2130 added support file
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  support/3114-mdms-data.json
Labels: UI

#2149 Feature 3114 ordertab main
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OrderName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/publishedNotificationModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  support/3114-mdms-data.json
Labels: UI

#2150 change pending task filter to search on filter text
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  support/3166-mdms-data.json
  support/3166-mdms-schema.json
Labels: UI

#2086 [bug-fix] #3359 "Upload Vakaltnama" to "Vakalatnama" fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  support/3359-mdms.json
Labels: UI

#2143 [enhancement-3386] Localisation Changes for iCops #3386
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
Labels: UI

#2144 [enhancement-3386] Localisation Changes for iCops
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
Labels: UI

#2132 transformer service from develop
  backend/transformer/src/main/java/org/egov/transformer/consumer/NotificationConsumer.java
  backend/transformer/src/main/java/org/egov/transformer/consumer/OrderConsumer.java
  backend/transformer/src/main/java/org/egov/transformer/controller/ScriptController.java
  backend/transformer/src/main/java/org/egov/transformer/event/impl/OrderImpl.java
Labels: Backend

#2160 hearing date BOTD bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2159 [hotfix-3155] COURTSTAFF: Added preview option for notices that are marked as Delivered /undelivered
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2157 [hotfix-3155] COURTSTAFF: Added preview option for notices that are marked as Delivered /undelivered
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2170 Fix for showing accused data in complaintTab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2171 Fix for showing accused data in complaintTab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2174 [hotfix-3323-toDev] Added submit Document button besides Make an Application button
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2173 [hotfix-3323] Added submit Document button besides Make an Application button
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2176 [bug-fix] #3362-Auto generated business of the day fixed for case dismissed #3414-Close button added
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#2177 [bug-fix] #3362 #3414 to develop
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#2178 Mar 12 merge main to develop fe
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponentsMulti.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/NextHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2180 [bug-3447] - e post page redirection fix and ui enhancement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomSortComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
Labels: UI

#2190 [bug-3342] - Update Summons/Notice/Warrant Pop-Up fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#2192 [Hotfix 3448-toDev] Fixed Preview status Issue in UAT CourtStaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2191 [bug-3342] - Update Summons/Notice/Warrant Pop-Up fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#2189 [hotfix-3448] Fixed Preview status Issue in UAT CourtStaff
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2185 [bug-3435] - action button fixed for bench clerk
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2184 [bug-3435] - action button fixed for bench clerk
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2188 [bug-fix] #3337-draft saved for arrow functionality fixed #3414-changed date format to DD-MM-YY
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ErrorsAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
Labels: UI

#2187 [bug-fix] #3337-draft saved for arrow functionality fixed #3414-changed date format to DD-MM-YY
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ErrorsAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
Labels: UI

#2196 Changes in summon template
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend

#2199 closing modal on bulk reschedule success
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
Labels: UI

#2198 closing modal on bulk reschedule success
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
Labels: UI

#2201 [bug-fix] #3261 Date Added changed to Date Issued
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
Labels: UI

#2200 [bug-fix] #3261 Date Added changed to Date Issued
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
Labels: UI

#2202 Revert changes related to pdf qr
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
Labels: UI

#2203 Hotfix 3159 summon pdf changes
  backend/summons-svc/src/main/java/digit/config/Configuration.java
  backend/summons-svc/src/main/java/digit/util/PdfServiceUtil.java
  backend/summons-svc/src/main/java/digit/web/models/SummonsPdf.java
  backend/summons-svc/src/main/resources/application.properties
Labels: Backend

#2213 Bulk E-Sign UI screens and Integration
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCopyTextDiv.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderAddToBulkSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderWorkflow.js
  frontend/micro-ui/web/src/setupProxy.js
  frontend/pucar-ui/web/micro-ui-internals/example/src/setupProxy.js
Labels: UI

#2216 added table task filter based on case name and filing Number
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
Labels: Backend

#2219 added table task filter based on case name and filing Number
  backend/task/src/main/java/org/pucar/dristi/repository/querybuilder/TaskCaseQueryBuilder.java
Labels: Backend

#2209 added condition to filter published orders for citizen
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#2215 Bug 3463 main
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#2218 [hotfix-3128] Fixed UI for opt-out Date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomChooseDate.js
Labels: UI

#2221 fix for Admit and Dismiss button should not show for case reached out…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2217 [hotfix-3128] Fixed UI for opt-out Date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomChooseDate.js
Labels: UI

#2210 [hotfix-3151] Added Tooltip for "Learn More" #3151
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
Labels: UI

#2211 [hotfix-3151] Added Tooltip for "Learn More" #3151
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/caseType.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
Labels: UI

#2232 remove the extra make another submission buttons
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#2234 calling case refetch on success
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
Labels: UI

#2228 [bug-fix] #3464 No one is not able to open dismissed cases Fixed || modal css issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#2229 [bug-fix] #3464 No one is not able to open dismissed cases Fixed || modal css issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/orders.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#2237 added support files for ticket 3367
  support/3367-mdms-data.json5
  support/3367-workflow.json5
Labels: Backend

#2242 [bug-fix] #3433 Join hearing button removed from Disposed Cases
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
Labels: UI

#2243 [bug-fix] #3433 Join hearing button removed from Disposed Cases
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
Labels: UI

#2248 added suggested css changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#2245 Enhancement 3342 3386 3414 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/GeoLocationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#2246 extractOrderNumber export change, advocateName fix in multiple adv case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/utils/extractOrderNumber.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2247 extractOrderNumber export change, advocateName fix in multiple adv case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/utils/extractOrderNumber.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2249 remove item in composite order bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2250 remove item in composite order bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2244 add advocate filter based on barId
  backend/advocate/src/main/java/org/pucar/dristi/repository/AdvocateRepository.java
  backend/advocate/src/main/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilder.java
  backend/advocate/src/main/java/org/pucar/dristi/service/AdvocateService.java
  backend/advocate/src/main/java/org/pucar/dristi/web/controllers/AdvocateApiController.java
  backend/advocate/src/main/java/org/pucar/dristi/web/models/AdvocateSimpleSearchRequest.java
  backend/advocate/src/test/java/org/pucar/dristi/repository/AdvocateRepositoryTest.java
  backend/advocate/src/test/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilderTest.java
  backend/advocate/src/test/java/org/pucar/dristi/service/AdvocateServiceTest.java
  backend/advocate/src/test/java/org/pucar/dristi/web/controllers/AdvocateApiControllerTest.java
Labels: Backend

#2256 Bulk sign redirection from tabs if in pending e-sign stage, added BOTD in additional details of order, download order on addBulk success fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/orderWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2255 Bulk sign redirection from tabs if in pending e-sign stage, added BOTD in additional details of order, download order on addBulk success fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/orderWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2258 hide Bulk sign for citizen, enable sign later for bench clerk
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderAddToBulkSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2260 Update Image-build-Inbox.yaml
  .github/workflows/Image-build-Inbox.yaml
Labels: Develop

#2261 Feature 3425 pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderAddToBulkSuccessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/orderHandlers/orderApprovalRejectionLitigantDetails.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2252 [hotfix-3473] FILING: Added infobox to complainaint address #3473
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  support/3473-mdms-data.json
Labels: UI

#2269 added police station in cheque details in mdms
  support/3358-mdms-data.json
Labels: UI

#2273 [bug-fix] #3145 Removed digit logo from title bar, added OnCourts logo
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/public/index.html
Labels: UI

#2274 Revert "revert those changes related to sorting based on caseID"
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
Labels: UI

#2275 Added Summons preview on view Case Page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SearchableDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2277 added tsb
  backend/treasury-backend/src/main/java/org/egov/eTreasury/config/PaymentConfiguration.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/ChallanDetails.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/TsbData.java
  backend/treasury-backend/src/main/resources/application.properties
Labels: Backend

#2283 Enhancement 3481 uat
  api_specifications/advocate-api-0.1.0.yaml
  backend/advocate/src/main/java/org/pucar/dristi/repository/AdvocateRepository.java
  backend/advocate/src/main/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilder.java
  backend/advocate/src/main/java/org/pucar/dristi/service/AdvocateService.java
  backend/advocate/src/main/java/org/pucar/dristi/web/controllers/AdvocateApiController.java
  backend/advocate/src/main/java/org/pucar/dristi/web/models/AdvocateSimpleSearchRequest.java
  backend/advocate/src/test/java/org/pucar/dristi/repository/AdvocateRepositoryTest.java
  backend/advocate/src/test/java/org/pucar/dristi/repository/querybuilder/AdvocateQueryBuilderTest.java
  backend/advocate/src/test/java/org/pucar/dristi/service/AdvocateServiceTest.java
  backend/advocate/src/test/java/org/pucar/dristi/web/controllers/AdvocateApiControllerTest.java
Labels: UI

#2281 [bugfix-3486] FSO: Give remarks option to the FSO
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2284 [enhancement-3481] Filing: 2 Registered advocate names are not showing to add them in the case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SearchableDropdown.js
Labels: UI

#2285 Bug 3485 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#2282 [bugfix-3486] FSO: Give remarks option to the FSO #3486
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/icons/svgIndex.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2299 fix related to botd and summons tags
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2300 Correct props passing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
Labels: UI

#2301 fix related to botd
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2306 revert " revert police Station changes "
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  support/3358-mdms-data.json
Labels: UI

#2324 [hotfix-3469-toDev] Magistrate: Esign symbol is showing on a order before doing Esign #3469
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2325 [hotfix-3469] Removed fileStoreId from local storage
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2291 added evidence search for pending e-sign state for bench clerk
  backend/evidence/src/main/java/org/pucar/dristi/config/ServiceConstants.java
  backend/evidence/src/main/java/org/pucar/dristi/enrichment/EvidenceEnrichment.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/EvidenceRepository.java
  backend/evidence/src/main/java/org/pucar/dristi/repository/querybuilder/EvidenceQueryBuilder.java
  backend/evidence/src/main/java/org/pucar/dristi/service/EvidenceService.java
  backend/evidence/src/main/java/org/pucar/dristi/web/models/Artifact.java
  backend/evidence/src/main/java/org/pucar/dristi/web/models/EvidenceSearchCriteria.java
  backend/evidence/src/test/java/org/pucar/dristi/service/EvidenceServiceTest.java
Labels: Backend

#2344 [Hotfix-3129-toDev] Made all hearings in just 1 slot and freezed time shown to advocates for case hearing to 11am
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: UI

#2348 join case replace task update after order generate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2351 [hotfix-3129] Updated next hearing time from mdms
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: UI

#2352 [hot-fix] #3547 Evidence Exhibit Number Missing & Removal of Unmarking - fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#2354 enhance litigant verification screen for replace advocate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
Labels: UI

#2356 [hotfix-3129-toDev] Removed filtering in BulkReschedule
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2358 [hot-fix] #3547 Evidence Exhibit Number Missing & Removal of Unmarking - fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ConfirmEvidenceAction.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2353 [hot-fix] #3547 Evidence Exhibit Number Missing & Removal of Unmarking - fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ConfirmEvidenceAction.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#2361 [hotfix-3129-toDev] Need to have all hearings in just 1 slot and freeze time shown to advocates for case hearing to 11am
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
Labels: UI

#2363 Join Case 2.0 - Disable case when advocate replace
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#2364 Join Case 2.0 - Disable case when advocate replac
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#2366 new bulk esign screens and integration
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/orderWorkflow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BulkCheckbox.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderBulkReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/3367-status-mdms-data.json
Labels: UI

#2371 Css version upgrade to qa
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#2374 [hotfix-3129-toDev] Need to have all hearings in just 1 slot and freeze time shown to advocates for case hearing to 11am
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2373 [hotfix-3129] Need to have all hearings in just 1 slot and freeze time shown to advocates for case hearing to 11am
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/usePreHearingModalData.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2376 [hot-fix] #3547 fixed exhibit numbering
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#2389 filterCriteria bug fix in bulk sign
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#2401 Join case enhance and bug
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiSelectDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2406 Profile edit join case changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#2408 Profile edit join case changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#2423 Rejected message for advocate replacement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2424 Rejected message for advocate replacement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2428 [hot-fix] #3535 fixed withdrawn application outcome on reject
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/3535-mdms.json
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2432 minor fixes for bulk signing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2429 [hotfix-3580] Witness Deposition not working as expected, unable to view after uploading #3580
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  support/3473-mdms-data.json
  support/3580-mdms-data.json
Labels: UI

#2430 [hotfix-3580-toDev] Witness Deposition not working as expected, unable to view after uploading #3580
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  support/3473-mdms-data.json
  support/3580-mdms-data.json
Labels: UI

#2437 [hotfix-3485-toDev] Benchclerk/Magistrate: Have Summons and warrants show in a row banner just like notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/NoticeAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2435 [hot-fix] #3535 fixed withdrawn application outcome
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/3535-mdms.json
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI
