Repository pucardotorg/dristi-solutions, pull requests merged in 2025-04, with the labels that each got.

#2507 Added for Majistrate needs an option to mention reason for Rejection …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js
Labels: UI

#2509 loading fix, localization change and preselect status filter
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersNotificationService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
Labels: UI

#2510 loading fix, localization change and preselect status filter
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BulkSignConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersNotificationService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
Labels: UI

#2512 Fix related to BOTD and Summons Tags
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2516 Added Hearing Date row in pending and sent tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
Labels: UI

#2514 [hotfix-3278] Judge page issues with longer case names
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2513 [hotfix-3278] Judge page issues with longer case names
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2528 [hot-fix] #3497 fixed esign for submit documents
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2539 [hot-fix] #3497 fixed post esign redirect
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SupportingDocsComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentEsign.js
Labels: UI

#2542 Fix for order Shifted to one
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2544 Fix for correct redirection of orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2552 Hotfix 3476 3644 uat redirection order type fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2549 Support file added #3497
  support/3497-mdms-role.json
Labels: mdms-changes

#2550 Support file added #3497
  support/3497-mdms-role.json
Labels: mdms-changes

#2546 [bug-fix] #3497 alignment fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
Labels: UI

#2555 [hot-fix] #3497 removed duplicate submission option and fixed submitted by name issue for clerk and judge
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2554 [hot-fix] #3497 removed duplicate submission option and fixed submitted by name issue for clerk and judge
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEvidenceDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2556 Application fee change from 2 to 20
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/PaymentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2570 Feature 3038
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/Dashboard.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/homeIcon.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/CustomDateRangePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
Labels: UI

#2574 updated iframe condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2575 Sending bill amount from Fetch Bill
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2576 Sending bill amount from Fetch Bill
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2578 getting reports from mdms
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2534 Add vakalatnama payment status and advocates count
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/VerifyMultipartyLitigantconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCasePayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/PendingTaskAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
Labels: UI

#2589 updated api for etreasury demand creation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useEtreasuryCreateDemand.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2591 Join case Payment fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
Labels: UI

#2592 fix(join-case): Improve payment flow and UI styling
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCasePayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
Labels: UI

#2590 updated css and loader instead of timer in report downloading
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/Dashboard.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2595 added logs
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2598 [bug-fix] #3411 - Voluntary Submission is displaying as status as completed Fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2597 [bug-fix] #3411 - Voluntary Submission is displaying as status as completed Fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2602 Enhance More precise Condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI

#2601 Enhance More precise Condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
Labels: UI

#2603 [bug-fix] Remove blocker #3411
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2607 [hot-fix] #3680 process banner for composite order fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2608 [bug-fix] #3411 minor bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2609 [bug-fix] #3411 minor bug fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2611 updated breakdown for application demand creation
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2613 [bug-fix] #3691 Fixed - hearing date displaying if hearing is not active
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2614 [bug-fix] #3691 Fixed - hearing date displaying if hearing is not active
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2616 [bug-fix] Minor fix #3411
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2617 [bug-fix] Minor fix #3411
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2622 POA config update, esign logic and pdf, parties tab visibility logic
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/service/caseService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomNote.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  support/3650-mdms-data.json
Labels: UI

#2623 fix: join case flow improvements and bug fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  support/3702-mdms-data.json
Labels: UI

#2627 placholder name fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#2625 [hot-fix] #3680 Fixed process banner for composite order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2633 updated env variables
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2634 Feature - 3650 Review case page change (POA)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  support/3650-mdms-data-review-case-file.json
Labels: UI

#2636 adding acronym for case pdf placeHolders, parties tab visibility fix
  backend/dristi-case-pdf/service/caseService.js
  backend/dristi-case-pdf/util/formatUtil.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#2638 removing extra spaces in acronym
  backend/dristi-case-pdf/util/formatUtil.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
Labels: UI

#2631 [bug-fix] #3661 Warrant payment issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2624 [hot-fix] #3680 Fixed process banner for composite order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2639 updated process env
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2641 updating esign panel condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#2650 memo return fix in esign page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#2630 [bug-fix] #3661 Warrant payment issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2652 POA holder Pending Task changes and review case file improvements
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/caseUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/utils/caseUtils.js
  support/3650-mdms-data-review-case-file.json
Labels: UI

#2656 feature: add join case in view case page #3650
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2658 added police station in cheque details
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  support/3358-mdms.json
Labels: UI

#2659 added police station in cheque details
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  support/3358-mdms.json
Labels: UI

#2665 Update navbar and admitted case header zIndex and positioning styles
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2668 poa join case revert
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2669 Update navbar and admitted case header zIndex and positioning styles
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2679 Remove ConfirmCorrectionModal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2680 Remove ConfirmCorrectionModal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2682 Update default isVakalatnamaNew values from "NO" to "YES"
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2671 [Enhancement-3486-toDev] FSO: Give remarks option to the FSO
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: enhancement

#2670 [Enhancement-3486] FSO: Give remarks option to the FSO
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: enhancement

#2681 Update default isVakalatnamaNew values from "NO" to "YES"
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
Labels: UI

#2684 Move the application Amount to mdms
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/PaymentModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  support/1.6.0-3711-mdms-schema.json
  support/1.6.0.3711-mdms-data.json
Labels: UI

#2708 POA FSO fix
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  support/3650-mdms-data-review-case-file.json
  support/3650-mdms-data.json
Labels: UI

#2688 For Schedule Next hearing Botd change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2687 For Schedule Next hearing Botd change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2705 updated css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  support/3038-mdms-data.json
  support/3038-mdms-schema.json
Labels: UI

#2715 Updated Application Fee Amount
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2714 Updated Application Fee Amount
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2716 setting purposeOfHearing from formData as well in botd of hearing date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2718 setting purposeOfHearing from formData as well in botd of hearing date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2717 updated css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2721 change the policeStation key for chequeDetails
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  support/3358-mdms.json
Labels: UI

#2720 change the policeStation key for chequeDetails
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  support/3358-mdms.json
Labels: UI

#2732 Sanitize noOfAdvocates input
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
Labels: UI

#2735 Sanitize noOfAdvocates input
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/LitigantVerification.js
Labels: UI

#2734 [hotfix-3485-toDev] Removed Process status banner from Advocate
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2736 update start date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#2743 Support files for landing page
  support/v1.6.0/43-landing-page-mdms-data.json
  support/v1.6.0/43-landing-page-mdms-schema.json
Labels: mdms-changes

#2744 Add bill details to handleButtonClick and update bill search params
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
Labels: UI

#2745 Add bill details to handleButtonClick and update bill search params
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
Labels: UI

#2755 key name for newHearingDate fix in reschedule hearing date order pdf
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#2756 key name for newHearingDate fix in reschedule hearing date order pdf
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#2758 new botd for Rescheduling of hearing date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2757 new botd for Rescheduling of hearing date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2767 Develop poa remaining
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultipleAdvocatesAndPip.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/3650-mdms-data-review-case-file.json
  support/3650-mdms-data.json
  support/3748-mdms-data.json
Labels: UI

#2770 fixing age field in scutiny page, showing FSO error for Id Proof on complainant page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  support/sprint 19 poa/3769-mdms-data.json
Labels: UI

#2781 Removed "Search Case Id" field from Total Hearings tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
Labels: UI

#2768 Fix for judgement Date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
Labels: UI

#2769 Fix for judgement Date
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
Labels: UI

#2785 adding poa in mark Attendence list, complainant pip yes/no
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/DisplayAttendees.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2766 Bail Application: Added 'OTHERS' to SubmissionDocumentType
  support/18.4/3500-mdms-data.json
Labels: mdms-changes

#2786 fixed esign pending tasks for poa
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
Labels: UI

#2765 Bail Application: Added 'OTHERS' to SubmissionDocumentType
  support/18.4/3500-mdms-data.json
Labels: mdms-changes

#2792 Complainant's Id issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
Labels: UI

#2793 Complainant's Id issue fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
Labels: UI

#2798 remove debugger
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
Labels: UI

#2800 Change deliveryChannel appearance for warrant Order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2801 Enhancment 3452 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2802 Fixed alignment of sort filters
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/pages/employee/SummonsNWarrantsModal.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/prehearing.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/homehearing.scss
Labels: UI

#2803 Fixed alignment of sort filters
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/pages/employee/SummonsNWarrantsModal.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/prehearing.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/homehearing.scss
Labels: UI

#2809 fix for enabling all section after case send back
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2810 [enhancement-3653] COURTSTAFF: Enhancement on Review Notice/Summons View
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: enhancement

#2811 [enhancement-3653] COURTSTAFF: Enhancement on Review Notice/Summons View
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: enhancement

#2813 Fix for auto populate police data
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2812 Fix for auto populate police data
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2817 Enhancement 3653
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
Labels: enhancement

#2816 Enhancement 3653 to dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/index.js
Labels: enhancement

#2818 remove case search and add caseId and caseTitle in PendingTasks
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentBreakdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2820 updated hearing logic in select custom date and css updated
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearings.js
Labels: UI

#2823 Changed "digit-ui" references to "ui"
  frontend/micro-ui/web/micro-ui-internals/example/package.json
  frontend/micro-ui/web/micro-ui-internals/example/src/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/SideBar/StaticCitizenSideBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBarComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/ApplicationAwaitingPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/LandingPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/TakeUserToRegistration.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Home/litigantHome/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/Login/SelectMobileNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/AdvocateClerkAdditionalDetail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectName.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsCondition.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/TermsConditions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/SubmissionsReview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ViewAllSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/src/App.js
  frontend/micro-ui/web/webpack.config.js
Labels: UI

#2788 Magistrate: Remove "Bench" from Type of Warrant
  support/18.4/3511-mdms-data.json
Labels: mdms-changes

#2826 remove caseSearch in hearings page also
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/Accordian.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
Labels: UI

#2833 fixing url in nyayMitra and added caseId, caseTitle in create task
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2836 updated code to avoid unnecessarily case refresh in case view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#2841 [hotfix-3826] Localisation Issue
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
Labels: UI

#2839 Refactor component for unintended rendering
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
Labels: UI

#2830 Make document as optional for other type application and remove auto …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#2849 Changed BOTD for bulk rescheduling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#2853 optimize AdmittedCase component performance and prevent unnecessary rerenders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2847 Removal of policeStation Condition on warrant
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
Labels: UI

#2856 shifting esign localStorage to sessionStorage, view case css change
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ESignSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDocUpload.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/signatureconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/WitnessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/CustomStepperSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewDocumentSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionDocumentEsign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SubmissionSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#2859 pending task bulkSign button fix, IssuedTo fix in pending Task
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2860 Issued To fix in payment modal for composite order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2846 Removal of policeStation Condition on warrant
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
Labels: UI

#2865 Make close button visible always when we open a document
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
Labels: UI

#2868 Case is having two Hearings fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EndHearing.js
Labels: UI

#2870 Remove useMemo hooks for simple variable assignments and role checks
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2872 Cases with hearings ended should also be navigatable from the calendar view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
Labels: UI

#2876 refactor case view component with perfomance optimizations
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI
