Repository pucardotorg/dristi-solutions, pull requests merged in 2025-06, with the labels that each got.

#3302 Esign Redirection Issue
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3303 Esign Redirection Issue (#3302)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useESign.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3325 Feature 3889 profile application pdf
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  support/1.6.8/3889-mdms-data.json
  utilities/dristi-pdf/src/applicationHandlers/applicationProfileEdit.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/routes/application.js
Labels: UI

#3331 Days Since Submitted fix for fso
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
Labels: UI

#3346 courtId dependency fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCasePayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/JudgementViewCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/SummaryModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3352 fix for joined accused
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
Labels: UI

#3370 Fix for Complaint Issue when case return from fso
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#3378 diabled typist action on review summon/warrant/notice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#3381 Feature 3991
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/21/3991-mdms-data.json
  utilities/dristi-pdf/src/api.js
  utilities/dristi-pdf/src/caseBundle/buildCasePdf.js
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processCourtEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processOrders.js
  utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processTaskProcesses.js
  utilities/dristi-pdf/src/caseBundle/sections/processTitlePageSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
  utilities/dristi-pdf/src/caseBundle/utils/applyDocketToDocument.js
  utilities/dristi-pdf/src/caseBundle/utils/combineMultipleFilestores.js
  utilities/dristi-pdf/src/caseBundle/utils/convertFileStoreToDocument.js
  utilities/dristi-pdf/src/caseBundle/utils/duplicateExistingFileStore.js
  utilities/dristi-pdf/src/caseBundle/utils/filterCaseBundleBySection.js
  utilities/dristi-pdf/src/caseBundle/utils/fixJpg.js
  utilities/dristi-pdf/src/caseBundle/utils/mergePDFDocuments.js
  utilities/dristi-pdf/src/caseBundle/utils/persistPDF.js
  utilities/dristi-pdf/src/caseBundle/utils/size.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/routes/pdfRoutes.js
Labels: UI

#3391 not showing tab if list is not present, payment children fix, added pendingApproval to pending Application, fixed dynamic section number for docket
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
  utilities/dristi-pdf/src/caseBundle/utils/getDynamicSectionNumber.js
Labels: UI

#3394 removed unnecessary import
  utilities/dristi-pdf/src/caseBundle/utils/getDynamicSectionNumber.js
Labels: UI

#3396 Develop to main 4076 4088
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/VerifyMultipartyLitigantconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCasePayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SummonsOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3393 added sorting based on lastmodified time
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#3405 updated total count
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3409 minor fix for affidavit section
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3410 Feature 3990 redirection enhancement
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3411 Feature 3990 redirection enhancement to main
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3417 showed rejected and pendingDocUpload applications, fixed localization in pdf docket
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
Labels: UI

#3426 fixed mark as evidence show only for judge in case view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3427 fixed docket and pagination of order in pdf
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processOrders.js
  utilities/dristi-pdf/src/caseBundle/sections/processTaskProcesses.js
Labels: UI

#3428 not re-directing to case view screen on start hearing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/SideBarItem.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3431 fixed mark as evidence in case file ui
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3432 [ICOPS Enhancement] Allow magistrate to issue miscellenious warrant/s…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
Labels: UI

#3441 hearing type field should have a scrolling option for dropdown fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/admission.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
Labels: UI

#3452 updated bread crump
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/Home.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/PaymentInbox.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/home/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/HearingOverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/index.js
Labels: UI

#3457 updated css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3459 Enhancement 4126 to dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3460 Fearure 3995 main dev
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/Home.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DRISTICard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Inbox/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/PaymentInbox.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/AdmissionActionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/home/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/HearingOverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/SideBarItem.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderIssueBulkSuccesModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/index.js
Labels: UI

#3463 updated localiztaion in hearing view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
Labels: UI

#3467 added validations and mdms data for icops subtype
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/1.7.0/3852-mdms-data.json
  support/1.7.0/3852-mdms-schema.json
Labels: UI

#3468 added loader
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3478 pagination fix in application, objection docket fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
Labels: UI

#3487 Prefiled details are appearing in Application details
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3488 Hotfix 3980 4104 to dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3491 Not able to proceed with the case, if the comp screen is "saved as d…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3499 Feature 3991 - case bundle pdf and ui changes
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/evidenceheader.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Utils/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseJudge.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  support/21/3991-mdms-data.json
  utilities/dristi-pdf/src/api.js
  utilities/dristi-pdf/src/caseBundle/buildCasePdf.js
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processCourtEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processOrders.js
  utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processTaskProcesses.js
  utilities/dristi-pdf/src/caseBundle/sections/processTitlePageSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
  utilities/dristi-pdf/src/caseBundle/utils/applyDocketToDocument.js
  utilities/dristi-pdf/src/caseBundle/utils/combineMultipleFilestores.js
  utilities/dristi-pdf/src/caseBundle/utils/convertFileStoreToDocument.js
  utilities/dristi-pdf/src/caseBundle/utils/duplicateExistingFileStore.js
  utilities/dristi-pdf/src/caseBundle/utils/filterCaseBundleBySection.js
  utilities/dristi-pdf/src/caseBundle/utils/fixJpg.js
  utilities/dristi-pdf/src/caseBundle/utils/getDynamicSectionNumber.js
  utilities/dristi-pdf/src/caseBundle/utils/mergePDFDocuments.js
  utilities/dristi-pdf/src/caseBundle/utils/persistPDF.js
  utilities/dristi-pdf/src/caseBundle/utils/size.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/routes/pdfRoutes.js
Labels: UI

#3504 changes for docket naeOfFiling and counsel in case bundle pdf
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
Labels: UI

#3505 changes for docket naeOfFiling and counsel in case bundle pdf
  utilities/dristi-pdf/src/caseBundle/sections/processAccusedEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processAdditionalFilings.js
  utilities/dristi-pdf/src/caseBundle/sections/processAffidavitSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processBailDocuments.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplainantEvidence.js
  utilities/dristi-pdf/src/caseBundle/sections/processComplaintSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processDisposedApplications.js
  utilities/dristi-pdf/src/caseBundle/sections/processFilingsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processMandatorySubmissions.js
  utilities/dristi-pdf/src/caseBundle/sections/processPaymentReceipts.js
  utilities/dristi-pdf/src/caseBundle/sections/processPendingApplicationsSection.js
  utilities/dristi-pdf/src/caseBundle/sections/processVakalatSection.js
Labels: UI

#3502 fixed dropdown selection for citizen hearing page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
Labels: UI

#3503 fixed dropdown selection for citizen hearing page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/WitnessDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
Labels: UI

#3506 [Feature - 4162] || Advocate Home Screen and Hearing Experience
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
Labels: UI

#3510 changes for direct submission documentTitle
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3519 page redirecting after clicking e-sign button
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
Labels: UI

#3513 Hotfix 3852 feature to uat
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  support/1.7.0/3852-mdms-data.json
  support/1.7.0/3852-mdms-schema.json
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
Labels: UI

#3535 fixed sectionNumber in async for case bundle pdf
  utilities/dristi-pdf/src/caseBundle/sections/processPendingAdmissionCase.js
Labels: UI

#3539 Bug 4053 4207 to develop
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#3541 adding confirmation popup when marking evidence from case file
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ConfirmEvidenceAction.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3546 Legal Benefit fund amount is not showing in Case filing payment receipt generated
  backend/treasury-backend/src/main/java/org/egov/eTreasury/config/ServiceConstants.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/enrichment/TreasuryEnrichment.java
  backend/treasury-backend/src/main/java/org/egov/eTreasury/model/TreasuryPaymentData.java
Labels: enhancement

#3548 Feature 4213
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BreadCrumb.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3552 Feature 4213 dev
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BreadCrumb.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/NextHearingCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeHeader.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkESignView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#3549 Fixed breadcrumb issues on refresh
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/InsideHearingMainPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3553 Feature 4213 (#3548)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
Labels: UI

#3554 paragragh tag is diplsying in downloaded PDF
  backend/dristi-case-pdf/controller/caseController.js
Labels: UI

#3563 added missing import
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
Labels: UI

#3568 updated-mdms-for-3852-uat
  support/v1.7.0/3852-mdms-data.json
  support/v1.7.0/3852-mdms-schema.json
Labels: UI

#3569 updated-mdms-for-3852-uat
  support/v1.7.0/3852-mdms-data.json
  support/v1.7.0/3852-mdms-schema.json
Labels: UI

#3579 creation of Grouped Dropdown for warrant
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomGroupedDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3580 creation of Grouped Dropdown for warrant
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomGroupedDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3587 added pagination in hearing home Screen and clean code in Home hearin…
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/useInboxSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3586 added pagination in hearing home Screen and clean code in Home hearin…
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/useInboxSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3585 Added "Save and Sign later" option to typist/clerk
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3590 Removed botd modal for ongoing hearing passed over
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3594 updated date validation condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
Labels: UI

#3592 support files for accept/reject order for settlement and transfer of case
  support/v1.7.1/4174-mdms.json
Labels: mdms-changes

#3595 NIA redirection link fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#3598 Added Forward/backward navigation arrow
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3607 Correction of Serial number on Pagination
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3608 Correction of Serial number on Pagination
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3610 redirection from case - back to home screen fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3617 support file for typist/clerk role
  support/v1.7.1/bug-4232-roles.json5
Labels: mdms-changes

#3620 Merge main to develop june 26 25 fe
  .github/workflows/Image-build-AB-diary.yaml
  .github/workflows/Image-build-Advocate.yaml
  .github/workflows/Image-build-Analytics.yaml
  .github/workflows/Image-build-Application.yaml
  .github/workflows/Image-build-Billing-Service.yaml
  .github/workflows/Image-build-Case.yaml
  .github/workflows/Image-build-CaseManagement.yaml
  .github/workflows/Image-build-Collection-Services.yaml
  .github/workflows/Image-build-Egov-Filestore.yaml
  .github/workflows/Image-build-Egov-Hrms.yaml
  .github/workflows/Image-build-Egov-Localization.yaml
  .github/workflows/Image-build-Egov-Mdms-Service.yaml
  .github/workflows/Image-build-Egov-User.yaml
  .github/workflows/Image-build-Egov-Workflow-V2.yaml
  .github/workflows/Image-build-Egov-indexer.yaml
  .github/workflows/Image-build-Epost-tracker.yaml
  .github/workflows/Image-build-Evidence.yaml
  .github/workflows/Image-build-Hearing.yaml
  .github/workflows/Image-build-Hearing_management.yaml
  .github/workflows/Image-build-Icops-integration.yaml
  .github/workflows/Image-build-Inbox.yaml
  .github/workflows/Image-build-Individual.yaml
  .github/workflows/Image-build-Notification.yaml
  .github/workflows/Image-build-Order-Management.yaml
  .github/workflows/Image-build-Order.yaml
  .github/workflows/Image-build-Payment-calculator.yaml
  .github/workflows/Image-build-Task.yaml
  .github/workflows/Image-build-Transformer.yaml
  .github/workflows/Image-build-dristi-case-pdf.yaml
  .github/workflows/Image-build-dristi-pdf.yaml
  .github/workflows/Image-build-e-sign-svc.yaml
  .github/workflows/Image-build-egov-apportion-service.yaml
  .github/workflows/Image-build-egov-idgen.yaml
  .github/workflows/Image-build-esign-interceptor.yaml
  .github/workflows/Image-build-etreasury-svc.yaml
  .github/workflows/Image-build-etreasury-ui.yaml
  .github/workflows/Image-build-gateway.yaml
  .github/workflows/Image-build-kerala-sms.yaml
  .github/workflows/Image-build-lock-svc.yaml
  .github/workflows/Image-build-notification-mail.yaml
  .github/workflows/Image-build-ocr-svc.yaml
  .github/workflows/Image-build-openapi.yaml
  .github/workflows/Image-build-sbi-svc.yaml
  .github/workflows/Image-build-sbi-ui.yaml
  .github/workflows/Image-build-summons-svc.yaml
  .github/workflows/Image-build-sunbirdrc.yaml
  .github/workflows/Image-build-user-otp.yaml
  .github/workflows/Image-build.yaml
  .github/workflows/image-build-Digit-Ui.yaml
  .github/workflows/image-build-pdf-service.yaml
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverviewV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
Labels: UI

#3628 CSS upgrade (#3627)
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#3646 Set default value to 30
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
Labels: UI

#3650 updated date field to have default value
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
Labels: UI

#3649 updated date field to have default value
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
Labels: UI

#3652 added filters in page redirection from homescreen to case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
Labels: UI

#3662 css fix
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
Labels: UI

#3626 added case view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseBundleView.js
Labels: UI

#3659 added loader
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
Labels: UI

#3677 Bug 4258 qa
  backend/treasury-webpage/app.js
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#3679 added validation for amount
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
Labels: UI

#3681 Address issue while registeration of user fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
Labels: UI

#3678 added validation for amount
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
Labels: UI

#3698 updated max amount condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PaymentDemandModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/GeneratePaymentDemandBreakdown.js
Labels: UI
