Repository pucardotorg/dristi-solutions, pull requests merged in 2025-10, with the labels that each got.

#4626 Task editor role for send and update
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4625 Task editor role for send and update
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4640 Css deploy oct 1
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#4658 Pending task name change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
Labels: UI

#4660 Sending POST in payload instead of EPOST
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: bug

#4661 Sending POST in payload instead of EPOST
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: bug

#4663 VIEW_SIGN_PROCESS role removal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/HomeSidebar.js
Labels: UI

#4666 Changes in canSign and btn visibility
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4675 Signed popup changed and bulk sign condition added
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: bug, UI

#4692 fixed redirection, scheduledHearing and count issue
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/TopBar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SendCaseBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/NewBulkRescheduleTable.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4696 Css deploy develop oct 6
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#4699 Btns to right in mozilla
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/home/home.scss
Labels: bug

#4704 Mark as sent removed for police and toast for unauthorized users
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: bug

#4706 fixed the Dom, console and some innerHtml windsurf issues
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/hooks/useIndividualView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/advocateRegistration.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DependentCheckBoxComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectTranscriptTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BreadCrumbHearings.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/ReSchedulHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/Transcription.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondSignModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkMarkAsEvidenceView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkSignADiaryView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/NewBulkRescheduleTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/WitnessDepositionSignModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/BreadCrumbsNew.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/MakeSubmissionBail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersCreate.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/UpdateEPostStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BreadCrumbSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/UICustomizations.js
  utilities/dristi-pdf/src/caseBundle/buildCasePdf.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/consumer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
Labels: UI

#4707 fixed the Dom, console and some innerHtml windsurf issues
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/hooks/useIndividualView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/advocateRegistration.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DependentCheckBoxComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/LocationSearch.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectTranscriptTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BreadCrumbHearings.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/ReSchedulHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/Transcription.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/usePaymentProcess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondSignModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkMarkAsEvidenceView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BulkSignADiaryView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeHearingsTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/NewBulkRescheduleTab.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/WitnessDepositionSignModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/BreadCrumbsNew.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/MakeSubmissionBail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/OrdersCreate.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/UpdateEPostStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BreadCrumbSubmissions.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/UICustomizations.js
  utilities/dristi-pdf/src/caseBundle/buildCasePdf.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/consumer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
Labels: UI

#4710 QA demo bug fixes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/OfflinePaymentsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/MainHomeScreen.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/NewBulkRescheduleTab.js
Labels: bug

#4718 Bulk download after bulk sign
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: enhancement

#4722 Redirect on esign resolved
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSignatureComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: bug
