Repository pucardotorg/dristi-solutions, pull requests merged in 2025-05, with the labels that each got.

#2879 switching billSearch to fetchBill for task related payments
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useFetchBill.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2867 Case is having two Hearings fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/EndHearing.js
Labels: UI

#2832 Homescreen Change CaseId -> Case Number
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#2850 [hotfix-3471] Changed BOTD for bulk rescheduling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#2873 Cases with hearings ended should also be navigatable from the calendar view
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/Modal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
Labels: UI

#2880 aded back search case Id field
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/PreHearingConfig.js
Labels: UI

#2829 Make document as optional for other type application and remove auto …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomDragDrop.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
Labels: UI

#2882 switching billSearch to fetchBill for task related payments (#2879)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useFetchBill.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2890 Enhancement on Review Notice/Summons View
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: enhancement

#2894 Removed "Powered by Digit" from footer
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ChangePassword/changePassword.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ForgotPassword/forgotPassword.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/LanguageSelection/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
Labels: UI

#2893 Removed "Powered by Digit" from footer
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ChangePassword/changePassword.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/ForgotPassword/forgotPassword.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/LanguageSelection/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/pages/employee/Login/login.js
Labels: UI

#2891 Feature 3779 3772 to main
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/LitigantHomePage.js
Labels: UI

#2885 added localization in document type
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
Labels: UI

#2896 added localization in document type (#2885)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
Labels: UI

#2889 Enhancement on Review Notice/Summons View
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: enhancement

#2900 updated filter condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#2899 updated filter condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
Labels: UI

#2906 added condition while showing actions in hearing tab
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2908 Fix date validation and add scrolling to litigant verification section
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#2917 Added prev hearing and show transcript for dismissed cases
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#2918 Added prev hearing and show transcript for dismissed cases
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/CaseOverview.js
Labels: UI

#2922 order pending task | On first access, any order with a pending task redirects to the home screen fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2923 edit case pendingTask fix while uploadDoc
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#2925 reIssue pending task fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#2931 hearing order has been published, but still the schedule hearing button is appearing fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2933 fixing consecutive api calls while creating composite order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2935 edit litigent details | taking more than 6 digits in pincode fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/Config/editComplainantDetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
Labels: UI

#2934 added fso case lock
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  support/19.2/2287-mdms-data.json
Labels: UI

#2939 Made Combined View for Notice, Summons and warrant process
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
Labels: UI

#2940 Made Combined View for Notice, Summons and warrant process
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
Labels: UI

#2930 Efiling screen proof of service of legal demand notice fields changed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/index.js
  support/19.2/3829-mdms-schema.json
Labels: UI

#2947 Added "Application Review" type in hearing mdms
  support/v1.6.4/3709-mdms-data.json
  support/v1.6.4/3829-mdms-schema.json
Labels: mdms-changes

#2946 Add Application Review as hearing type in MDMS
  support/v1.6.4/2287-mdms-data.json
  support/v1.6.4/3709-mdms-data.json
  support/v1.6.4/3829-mdms-schema.json
Labels: mdms-changes

#2928 Remove fields showing "OutlinedInfoIcon" once a case is sent back
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2926 Remove fields showing "OutlinedInfoIcon" once a case is sent back
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: UI

#2950 update the ui screen to respective figma
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2949 Hotfix 3452 new figma
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantOrderComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2948 NonWorking days marked as red in Calendar
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
Labels: UI

#2944 NonWorking days marked as red in Calendar
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
Labels: UI

#2956 Added bydefault for via police and fix for trim text
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2955 Added bydefault for via police and fix for trim text
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/WarrantRenderDeliveryChannels.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2959 updated url in notice demand error modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#2964 changed hearing search api
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearingCounts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#2966 hrms implementation for court and judge details in pdfs
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/UpComingHearing.js
  utilities/dristi-pdf/src/api.js
  utilities/dristi-pdf/src/applicationHandlers/applicationBailBond.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
  utilities/dristi-pdf/src/caseBundle/generateIndex.js
  utilities/dristi-pdf/src/config.js
  utilities/dristi-pdf/src/hearingHandlers/hearingBulkReschedule.js
  utilities/dristi-pdf/src/orderHandlers/acceptReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/adrCaseReferral.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/caseSettlementRejection.js
  utilities/dristi-pdf/src/orderHandlers/caseTransfer.js
  utilities/dristi-pdf/src/orderHandlers/mandatoryAsyncSubmissionsResponses.js
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderAcceptanceRejectionDca.js
  utilities/dristi-pdf/src/orderHandlers/orderAdmitCase.js
  utilities/dristi-pdf/src/orderHandlers/orderApprovalRejectionLitigantDetails.js
  utilities/dristi-pdf/src/orderHandlers/orderBailAcceptance.js
  utilities/dristi-pdf/src/orderHandlers/orderBailRejection.js
  utilities/dristi-pdf/src/orderHandlers/orderChangeAdvocate.js
  utilities/dristi-pdf/src/orderHandlers/orderDismissCase.js
  utilities/dristi-pdf/src/orderHandlers/orderForRejectionReschedulingRequest.js
  utilities/dristi-pdf/src/orderHandlers/orderGeneric.js
  utilities/dristi-pdf/src/orderHandlers/orderNotice.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectCheckout.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectExtension.js
  utilities/dristi-pdf/src/orderHandlers/orderRejectVoluntary.js
  utilities/dristi-pdf/src/orderHandlers/orderSection202crpc.js
  utilities/dristi-pdf/src/orderHandlers/orderSetTermsOfBail.js
  utilities/dristi-pdf/src/orderHandlers/orderWarrant.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalAccept.js
  utilities/dristi-pdf/src/orderHandlers/orderWithdrawalReject.js
  utilities/dristi-pdf/src/orderHandlers/scheduleHearingDate.js
  utilities/dristi-pdf/src/orderHandlers/summonsIssue.js
  utilities/dristi-pdf/src/routes/application.js
  utilities/dristi-pdf/src/routes/order.js
  utilities/dristi-pdf/src/utils/commonUtils.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#2967 Employee Reset password implementation UI
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/TopBarSideBar/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EmployeeProfileEdit/EmployeeProfileEdit.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageUpload/UploadDrawer.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/index.js
Labels: UI

#2968 Dev to main nk
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/cases/pages/employeee/joinCaseHome.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/Config/editComplainantDetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#2970 updated key
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearingCounts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2979 updated boolen condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
Labels: UI

#2974 added fso case lock (#2934)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  support/v1.6.4/2287-mdms-data.json
Labels: UI

#2976 added condition while showing actions in hearing tab (#2906)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/OverlayDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#2990 Added Process Fee Paid on Date in Review Summon, Warrant & Notices.
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2989 Added Process Fee Paid on Date in Review Summon, Warrant & Notices.
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#2995 Feature 3771 main
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderSignatureModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#2997 Feature 3872 reIssue pending task fix, edit case pendingTask fix while uploadDoc
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/CaseLockModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
Labels: UI

#3000 Feature 3770 main
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/Accordian.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/TaskComponentCalander.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentBreakdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/EfilingPaymentDropdown.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleNextHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/SBIEpostPayment.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionDocuments.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3005 added caseId and caseTitle in url for ReIssueNotice
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
Labels: UI

#2992 Feature 3773 main
  frontend/micro-ui/web/micro-ui-internals/example/src/setupProxy.js
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/PreHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearingCounts.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/src/setupProxy.js
Labels: UI

#3015 updated misssed code from dev to main
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/hooks/hearings/useGetHearings.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#3019 hrms filter in pdf bug fix
  utilities/dristi-pdf/src/utils/commonUtils.js
Labels: UI

#3020 hrms filter in pdf bug fix
  utilities/dristi-pdf/src/utils/commonUtils.js
Labels: UI

#3021 updated to delete unsigned filestore
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  support/v1.6.4/2287-mdms-data.json5
Labels: UI

#3022 fixed signature placeholder for judge
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#3023 fixed signature placeholder for judge
  utilities/dristi-pdf/src/orderHandlers/newHearingDateAfterReschedule.js
Labels: UI

#3027 updated filestore deleted condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3031 changing redirection of bulkSign popup close
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3032 changing redirection of bulkSign popup close
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/CalendarView.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
Labels: UI

#3033 adding document id in old documents
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3046 added prayer fields, space before placeholder and some css change in all applications
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiUploadWrapper.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
Labels: UI

#3047 added prayer fields, space before placeholder and some css change in all applications
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiUploadWrapper.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/UploadFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/configs/submissionsCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseTransfer.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCaseWithdrawal.js
  utilities/dristi-pdf/src/applicationHandlers/applicationCheckout.js
  utilities/dristi-pdf/src/applicationHandlers/applicationDelayCondonation.js
  utilities/dristi-pdf/src/applicationHandlers/applicationGeneric.js
  utilities/dristi-pdf/src/applicationHandlers/applicationProductionOfDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/applicationRescheduleRequest.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmissionExtension.js
  utilities/dristi-pdf/src/applicationHandlers/applicationSubmitBailDocuments.js
  utilities/dristi-pdf/src/applicationHandlers/caseSettlementApplication.js
Labels: UI

#3042 Removed freezing of upper half of View Case page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#3043 Removed freezing of upper half of View Case page
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#3048 updated css
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#3050 updated css (#3048)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomReviewCardRow.js
Labels: UI

#3053 made the case Timeline upto register
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#3057 fixed setBailTerm pending task and submit button condition
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3055 Removing Content box/Adding Content box data while passing Judgement …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#3052 made the case Timeline upto register
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#3065 switched fetchBill to billSearch, download bulk order fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pageComponents/OrderReviewModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
Labels: UI

#3064 migrate case search API from v1 to v2 with updated response structure
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SearchCaseAndShowDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useCaseDetailSearchService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Judge/JudgeInboxConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3070 fix: update case number display
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SearchCaseAndShowDetails.js
Labels: UI

#3058 Added preview of documents during registration approval on Nyaymitra
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DocumentDetailCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#3059 Added preview of documents during registration approval on Nyaymitra
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DocumentDetailCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#3073 Added preview of uploaded document
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
Labels: UI

#3074 Added preview of uploaded document
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectMultiUpload.js
Labels: UI

#3079 User Registration with Seperate Address
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#3080 Enhacment 3932 sepearte address dev
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/AddressComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserAddress.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/SelectUserType.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/registration/config.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
Labels: UI

#3083 Add Date on which payment pending and date on which payment was compl…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
Labels: UI

#3087 Show some more data when Nyaymitra clicks on a pending payment case
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
Labels: UI

#3086 Payment breakdown fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#3093 feat: add vakalatnama document viewer to advocate replacement component
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
Labels: UI

#3099 Case is not filing due to accused address details are not adding fixed and add mdms config
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  support/current-sprint/3970-mdms-complainant-config.json
  support/current-sprint/3970-mdms-respondent-config.json
Labels: UI

#3104 updated url in notice demand error modal (#2959)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3105 Upgrade css version (#3102)
  frontend/micro-ui/web/micro-ui-internals/example/public/index.html
  frontend/micro-ui/web/micro-ui-internals/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/css/package.json
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
Labels: UI

#3108 Bug 3947 3960 enhance 3675 to main
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SearchCaseAndShowDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/complaindetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/respondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  support/current-sprint/3970-mdms-complainant-config.json
  support/current-sprint/3970-mdms-respondent-config.json
Labels: UI

#3109 change the font size for hearing transcipt summary
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/HearingTranscriptModal.js
Labels: UI

#3112 feat: add vakalatnama document viewer to advocate replacement component
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
Labels: UI

#3117 Minor issues fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/Module.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/DocumentDetailCard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ImageModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/MultiUploadWrapper.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/ApplicationDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/docViewerWrapper.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/AddSubmissionDocument.js
Labels: UI

#3120 poa new user registration fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3128 Remove Extra Commnets other tha fso and judge
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js
Labels: UI

#3129 Remove Extra Commnets other tha fso and judge
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/WorkflowTimeline.js
Labels: UI

#3140 showing payment receipt in fso review page (#3091)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectReviewAccordion.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI

#3084 Add Date on which payment pending and date on which payment was compl…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
Labels: UI

#3143 Enhancement: Add functionality for fetching and previewing police station report
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useDownloadCasePdf.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
Labels: enhancement, UI

#3066 updated filestore delete
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useNewFilestoreId.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3150 css fixed for document view in applications
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/pages/employee/nyayMitra.scss
Labels: UI

#3158 Add Document Preview in Consolidated Notice View
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/SummonsNWarrantConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReviewNoticeModal.js
Labels: UI

#3159 Added Reson for Filing Info in evidence modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#3161 revert back the changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerificationComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
Labels: UI

#3165 updated file name
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
Labels: UI

#3166 Minor css fixes
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/submissions/submissionApplication.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#3167 Minor css fixes
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/submissions/submissionApplication.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
Labels: UI

#3169 added Other Type for Notices, Summons and Warrants
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/NoticeProcessModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/UpdateDeliveryStatusComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  support/v1.6.6/3698-mdms-data.json
Labels: UI

#3171 Have permanent as well as residential address of complainant during filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  support/21/3930-mdms-complainant-config.json
  support/21/3930-mdms-reviewCaseFile-config.json
Labels: enhancement

#3160 Added Reson for Filing Info in evidence modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#3172 Have permanent as well as residential address of complainant during filing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectComponents.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/Config/reviewcasefileconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  support/21/3930-mdms-complainant-config.json
  support/21/3930-mdms-reviewCaseFile-config.json
Labels: enhancement

#3177 updated adiary to delete file on esign
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
Labels: UI

#3164 Change CourtId from JudgeId for Adiary
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
Labels: UI

#3184 Feature 1924 main
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/components/datewrap.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/CustomCalendar.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useNewFilestoreId.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/ComplainantSignature.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3179 migrate case search API from v1 to v2 with updated response structure…
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/JoinCaseHome.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/JoinCaseSuccess.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SearchCaseAndShowDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useCaseDetailSearchService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Judge/JudgeInboxConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/BenchHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/CourtRoomHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/FSOHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/JudgeHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/LitigantHomeConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3192 added access of adiary to clerk
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3196 remove hardcoded court ID from case search criteria
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
Labels: UI

#3198 add case list search endpoint and service with updated UI integration
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useSearchCaseListService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3199 change courtId from JudgeId
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
Labels: UI

#3201 Allow Custom Dates in Bulk Rescheduling
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/BulkReschedule.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleTable.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#3163 Change CourtId from JudgeId for Adiary
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ADiaryPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3210 Issue notice after hearing scheduled order - fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/orders/useSearchOrdersService.js
Labels: UI

#3211 fixing nyay mitra filters
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
Labels: UI

#3212 fixing nyay mitra filters
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/paymentInboxConfig.js
Labels: UI

#3215 Change to courtId form JudgeId
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/PublishedOrderModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/publishedNotificationModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#3218 auto-populate name fields when verifying phone number fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
Labels: UI

#3219 auto-populate name fields when verifying phone number fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
Labels: UI

#3233 UI re-directed to Error window after clicking on Profile icon fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js
Labels: UI

#3232 UI re-directed to Error window after clicking on Profile icon fixed
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/eFiling.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/components/ChangeLanguage.js
Labels: UI

#3234 Merge main frontend to develop 26 May
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/dristi/useSearchCaseListService.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/hooks/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EfilingValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
  frontend/micro-ui/web/package.json
  frontend/micro-ui/web/public/index.html
  support/2494-mdms-data.json
Labels: UI

#3244 fixing case list api payload
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/HomeView.js
Labels: UI

#3245 Build Failed Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/package.json
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js
Labels: UI

#3256 Created Application Flow for Profile Edititng
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/Config/editComplainantDetailsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/Config/editRespondentConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/EditProfile.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/view-case/editProfileValidationUtils.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/ReviewLitigantDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/ReviewSubmissionModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#3260 Added Html to plain Text Conversion for complaint
  backend/dristi-case-pdf/controller/caseController.js
  backend/dristi-case-pdf/package.json
  backend/dristi-case-pdf/util/htmlToFormattedText.js
Labels: UI

#3265 Have document title appear in filing name (case view)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#3264 Have document title appear in filing name (case view)
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#3268 Minor bugfix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/citizen/FileCase/EFilingCases.js
Labels: bug

#3274 Change of the order name for admit case to take cognizance
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#3279 add screen-specific name field population in phone verification flow
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/configs/VerifyMultipartyLitigantconfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/VerifyPhoneNumber.js
Labels: UI

#3266 Allow Custom Dates in Bulk Rescheduling
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/hearings/BulkReschedule.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/BulkRescheduleTable.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/components/CustomDatePicker.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/BulkReschedule.js
Labels: UI

#3284 Change of the order name for admit case to take cognizance
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrders.js
  utilities/dristi-pdf/src/utils/orderUtils.js
Labels: UI

#3282 add disbality for text fiedl when fso returned
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js
Labels: UI

#3288 updated password
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/Dashboard.js
Labels: UI

#3295 fso judgeId fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/scrutiny/ViewCaseFile.js
Labels: UI
