Repository pucardotorg/dristi-solutions, pull requests merged in 2025-09, with the labels that each got.

#4331 Fix related to Revocation of Existing Power of Attorney
  utilities/dristi-pdf/src/applicationHandlers/applicationPoaClaim.js
Labels: UI

#4333 revert " An adv is not able to join to the comp, if that complainant …
  frontend/micro-ui/web/micro-ui-internals/packages/modules/cases/src/pages/employee/joinCaseComponent/SelectParty.js
Labels: UI

#4342 fixed accused details in order pdf
  utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
Labels: UI

#4351 fixed pendingTask redirection for Schedule Hearing
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/HomeConfig.js
Labels: UI

#4353 Fix related to add order item, publish order fail
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4354 Fix related to add order item, publish order fail
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  utilities/dristi-pdf/src/orderHandlers/formatDate.js
Labels: UI

#4367 Fix related to party type and application Number
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderUtils.js
Labels: UI

#4368 Fix related to party type and application Number
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderUtils.js
Labels: UI

#4370 Enhancement 4542 dev
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/witnessDepositionSignature.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/pages/citizen/userRegistration.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/index.scss
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/submissions/submissionApplication.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/core/src/App.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/BailEsignModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/components/SuccessBannerModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondLoginPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/BailBondSignaturePage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionLoginPage.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/WitnessDepositionSignaturePage.js
Labels: UI

#4375 Added some new form field
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderUtils.js
Labels: UI

#4376 added richText in itemText, added scheduledHearingNumber
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModalSMSAndEmail.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
  utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
Labels: UI

#4379 fixed orderTitle issue
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderApiCallUtils.js
Labels: UI

#4386 Parties tab tooltip fixed
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
Labels: UI

#4392 fixed itemText box, added NextHearingDate new logic, fixed schedulingHearingNumber
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/dristi/components/customTextArea.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  utilities/dristi-pdf/src/utils/htmlToFormattedText.js
Labels: UI

#4399 support files for Landing page caseStatus filter
  support/v1.10.1-sprint-24.1/4523-mdms-data.json
  support/v1.10.1-sprint-24.1/4523-mdms-schema.json
Labels: mdms-changes

#4404 added delete draft functionality for new orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EditSendBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
Labels: UI

#4403 added delete draft functionality for new orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/EditSendBackModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCasesConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/OrderDrafts.js
Labels: UI

#4405 Add CaseNumber in UpdateOrder
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4417 Disposed cases are restricted in LPR
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: bug

#4424 Suggested Changes Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#4426 Suggested Changes Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/ordersCreateConfig.js
Labels: UI

#4431 View case page "end Hearing" functionality changes for clerk and CRM
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
Labels: UI

#4437 fixed mandatory field issue in attendees in order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4445 Create 4457-update-isactive-mdms-data.json
  support/v1.11.0-sprint-25/4457-mdms-data.json
Labels: mdms-changes

#4451 added action field for functional specs -advocate replacement request
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
Labels: UI

#4450 added action field for functional specs -advocate replacement request
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
Labels: UI

#4459 fixed NextHearingButton issue, orderTitle and dropdown fix in orders
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/utils/orderApiCallUtils.js
Labels: UI

#4460 small fix - Pass over and End hearing buttons color and text changes
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
Labels: UI

#4464 Custom Text Editor Changes Fix
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/SelectCustomFormatterTextArea.js
Labels: UI

#4466 Enhancement 4635 dev
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4468 added new order template change, fixed nextHearing button logic, fixed autosaving in order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
Labels: UI

#4469 added new order template change, fixed nextHearing button logic, fixed autosaving in order
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  utilities/dristi-pdf/src/orderHandlers/newOrderGeneric.js
Labels: UI

#4471 Cherry pick to release25
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  support/v1.11.0-sprint-25/4313-mdms-data.json
  support/v1.11.0-sprint-25/4457-order-mdms-data.json
Labels: UI, mdms-changes

#4521 Remove Attendees bar from transcript modal
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/ShowAllTranscriptModal.js
Labels: UI

#4527 Enable attendee when all selected absent
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4564 Bulk actions
  frontend/micro-ui/web/micro-ui-internals/packages/css/src/orders/reviewsummons.scss
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/components/BulkCheckbox.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/Urls.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/hooks/services/index.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4556 Pending Task new Role Update
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCase.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/AdmittedCaseV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/AdmittedCases/EvidenceModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/Payment/ViewPaymentDetails.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/CaseFileAdmission.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/dristi/src/pages/employee/admission/ScheduleHearingModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/hearings/src/pages/employee/SummonsAndWarrantsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/AdvocateReplacementComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/components/TaskComponent.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/BailBondModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/pages/employee/ScheduleHearing.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/ReIssueSummonsModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/components/SBIPaymentStatus.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/E-PostTracking.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForRPADModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/PaymentForSummonModal.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4567 Fix for clear the hearing date on clik on skipScheduling
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/GenerateOrdersV2.js
Labels: UI

#4581 show dca when in pending/review
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#4582 show dca when in pending/review
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#4593 multiple dca can be raised
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#4594 multiple dca can be raised
  frontend/micro-ui/web/micro-ui-internals/packages/modules/submissions/src/pages/employee/SubmissionsCreate.js
Labels: UI

#4598 Updated payload with applicationStatus for tab change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4599 Updated payload with applicationStatus for tab change
  frontend/micro-ui/web/micro-ui-internals/packages/modules/home/src/configs/UICustomizations.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: UI

#4623 Bulk download failure handling and Search and btn for CMO
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/configs/SuumonsConfig.js
  frontend/micro-ui/web/micro-ui-internals/packages/modules/orders/src/pages/employee/ReviewSummonsNoticeAndWarrant.js
Labels: bug
